import { Vars, MaybeVar, Color, Dp, FocusIndicatorRef, ShapeRadii, ShapesRef, Ui } from "@internal/prelude";

export interface Checkbox {
  readonly containerSize: Dp,
  readonly containerShape: MaybeVar<ShapeRadii>,
  readonly iconSize: Dp,
  readonly touchTargetSize: Dp,

  readonly stateLayerSize: Dp,
  readonly stateLayerShape: MaybeVar<ShapeRadii>,
  readonly focusIndicatorColor: MaybeVar<Color>,
  readonly focusIndicatorThickness: MaybeVar<Dp>,
  readonly focusIndicatorOffset: MaybeVar<Dp>,

  readonly errorredHoveredStateLayerColor: MaybeVar<Color>,
  readonly errorredHoveredStateLayerOpacity: MaybeVar<Opacity>,
  readonly errorredFocusedStateLayerOpacity: MaybeVar<Opacity>,
  readonly errorredFocusedStateLayerColor: MaybeVar<Color>,
  readonly errorredPressedStateLayerColor: MaybeVar<Color>,
  readonly errorredPressedStateLayerOpacity: MaybeVar<Opacity>,

  readonly selectedContainerColor: MaybeVar<Color>,
  readonly selectedIconColor: MaybeVar<Color>,
  readonly selectedOutlineWidth: Dp,

  readonly selectedDisabledContainerColor: MaybeVar<Color>,
  readonly selectedDisabledContainerOpacity: MaybeVar<Opacity>,
  readonly selectedDisabledContainerOutlineWidth: Dp,
  readonly selectedDisabledIconColor: MaybeVar<Color>,

  readonly selectedHoveredContainerColor: MaybeVar<Color>,
  readonly selectedHoveredStateLayerColor: MaybeVar<Color>,
  readonly selectedHoveredStateLayerOpacity: MaybeVar<Opacity>,
  readonly selectedHoveredIconColor: MaybeVar<Color>,
  readonly selectedHoveredOutlineWidth: Dp,

  readonly selectedFocusedContainerColor: MaybeVar<Color>,
  readonly selectedFocusedStateLayerColor: MaybeVar<Color>,
  readonly selectedFocusedStateLayerOpacity: MaybeVar<Opacity>,
  readonly selectedFocusedIconColor: MaybeVar<Color>,
  readonly selectedFocusedOutlineWidth: Dp,

  readonly selectedPressedContainerColor: MaybeVar<Color>,
  readonly selectedPressedStateLayerColor: MaybeVar<Color>,
  readonly selectedPressedStateLayerOpacity: MaybeVar<Opacity>,
  readonly selectedPressedIconColor: MaybeVar<Color>,
  readonly selectedPressedOutlineWidth: Dp,

  readonly selectedErroredIconColor: MaybeVar<Color>,
  readonly selectedErroredHoveredContainerColor: MaybeVar<Color>,
  readonly selectedErroredHoveredIconColor: MaybeVar<Color>,
  readonly selectedErroredFocusedContainerColor: MaybeVar<Color>,
  readonly selectedErroredFocusedIconColor: MaybeVar<Color>,
  readonly selectedErroredPressedContainerColor: MaybeVar<Color>,
  readonly selectedErroredPressedIconColor: MaybeVar<Color>,

  readonly unselectedOutlineColor: MaybeVar<Color>,
  readonly unselectedOutlineWidth: Dp,

  readonly unselectedErroredContainerColor: MaybeVar<Color>,
  readonly unselectedErroredHoveredOutlineColor: MaybeVar<Color>,
  readonly unselectedErroredFocusedOutlineColor: MaybeVar<Color>,
  readonly unselectedErroredOutlineColor: MaybeVar<Color>,
  readonly unselectedErroredPressedOutlineColor: MaybeVar<Color>,

  readonly unselectedDisabledContainerOpacity: MaybeVar<Opacity>,
  readonly unselectedDisabledOutlineColor: MaybeVar<Color>,
  readonly unselectedDisabledOutlineWidth: Dp,

  readonly unselectedHoveredStateLayerColor: MaybeVar<Color>,
  readonly unselectedHoveredStateLayerOpacity: MaybeVar<Opacity>,
  readonly unselectedHoveredOutlineColor: MaybeVar<Color>,
  readonly unselectedHoveredOutlineWidth: Dp,

  readonly unselectedFocusedStateLayerColor: MaybeVar<Color>,
  readonly unselectedFocusedStateLayerOpacity: MaybeVar<Opacity>,
  readonly unselectedFocusedOutlineColor: MaybeVar<Color>,
  readonly unselectedFocusedOutlineWidth: Dp,

  readonly unselectedPressedStateLayerColor: MaybeVar<Color>,
  readonly unselectedPressedStateLayerOpacity: MaybeVar<Opacity>,
  readonly unselectedPressedOutlineColor: MaybeVar<Color>,
  readonly unselectedPressedOutlineWidth: Dp,
}

export const create = (): Checkbox => {
  return {
    containerSize: Dp.create(18),
    containerShape: ShapeRadii.all(Dp.create(2)),
    selectedContainerColor: Vars.ColorScheme.Primary(),
    unselectedErroredContainerColor: Vars.ColorScheme.Error(),
    unselectedDisabledContainerOpacity: Ui.create(0.38),
    selectedDisabledContainerColor: Vars.ColorScheme.OnSurface(),
    selectedDisabledContainerOpacity: Ui.create(0.38),
    selectedHoveredContainerColor: Vars.ColorScheme.Primary(),
    selectedErroredHoveredContainerColor: Vars.ColorScheme.Error(),
    selectedFocusedContainerColor: Vars.ColorScheme.Primary(),
    selectedErroredFocusedContainerColor: Vars.ColorScheme.Error(),
    selectedPressedContainerColor: Vars.ColorScheme.Primary(),
    selectedErroredPressedContainerColor: Vars.ColorScheme.Error(),
    selectedDisabledContainerOutlineWidth: Dp.create(0),
    stateLayerSize: Dp.create(40),
    stateLayerShape: Vars.ShapeScheme.Full(),
    selectedHoveredStateLayerColor: Vars.ColorScheme.Primary(),
    selectedHoveredStateLayerOpacity: Vars.Opacities.Hovered(),
    unselectedHoveredStateLayerColor: Vars.ColorScheme.OnSurface(),
    unselectedHoveredStateLayerOpacity: Vars.Opacities.Hovered(),
    errorredHoveredStateLayerColor: Vars.ColorScheme.Error(),
    errorredHoveredStateLayerOpacity: Vars.Opacities.Hovered(),
    focusIndicatorColor: Vars.ColorScheme.Secondary(),
    focusIndicatorThickness: Vars.FocusIndicator.Thickness(),
    focusIndicatorOffset: Vars.FocusIndicator.OuterOffset(),
    errorredFocusedStateLayerOpacity: Vars.Opacities.Focused(),
    selectedFocusedStateLayerColor: Vars.ColorScheme.Primary(),
    selectedFocusedStateLayerOpacity: Vars.Opacities.Focused(),
    unselectedFocusedStateLayerColor: Vars.ColorScheme.OnSurface(),
    unselectedFocusedStateLayerOpacity: Vars.Opacities.Focused(),
    errorredFocusedStateLayerColor: Vars.ColorScheme.Error(),
    unselectedPressedStateLayerColor: Vars.ColorScheme.Primary(),
    unselectedPressedStateLayerOpacity: Vars.Opacities.Pressed(),
    selectedPressedStateLayerColor: Vars.ColorScheme.OnSurface(),
    selectedPressedStateLayerOpacity: Vars.Opacities.Pressed(),
    errorredPressedStateLayerColor: Vars.ColorScheme.Error(),
    errorredPressedStateLayerOpacity: Vars.Opacities.Pressed(),
    iconSize: Dp.create(18),
    selectedIconColor: Vars.ColorScheme.OnPrimary(),
    selectedErroredIconColor: Vars.ColorScheme.OnError(),
    selectedDisabledIconColor: Vars.ColorScheme.Surface(),
    selectedHoveredIconColor: Vars.ColorScheme.OnPrimary(),
    selectedErroredHoveredIconColor: Vars.ColorScheme.OnError(),
    selectedFocusedIconColor: Vars.ColorScheme.OnPrimary(),
    selectedErroredFocusedIconColor: Vars.ColorScheme.OnError(),
    selectedPressedIconColor: Vars.ColorScheme.OnPrimary(),
    selectedErroredPressedIconColor: Vars.ColorScheme.OnError(),
    unselectedOutlineColor: Vars.ColorScheme.OnSurfaceVariant(),
    unselectedOutlineWidth: Dp.create(2),
    selectedOutlineWidth: Dp.create(0),
    unselectedErroredOutlineColor: Vars.ColorScheme.Error(),
    unselectedDisabledOutlineColor: Vars.ColorScheme.OnSurface(),
    unselectedDisabledOutlineWidth: Dp.create(2),
    unselectedHoveredOutlineColor: Vars.ColorScheme.OnSurface(),
    unselectedHoveredOutlineWidth: Dp.create(2),
    selectedHoveredOutlineWidth: Dp.create(0),
    unselectedErroredHoveredOutlineColor: Vars.ColorScheme.Error(),
    unselectedFocusedOutlineColor: Vars.ColorScheme.OnSurface(),
    unselectedFocusedOutlineWidth: Dp.create(2),
    selectedFocusedOutlineWidth: Dp.create(0),
    unselectedErroredFocusedOutlineColor: Vars.ColorScheme.Error(),
    unselectedPressedOutlineColor: Vars.ColorScheme.OnSurface(),
    unselectedPressedOutlineWidth: Dp.create(2),
    selectedPressedOutlineWidth: Dp.create(0),
    unselectedErroredPressedOutlineColor: Vars.ColorScheme.Error(),
    touchTargetSize: Dp.create(48),
  };
};