import { Color, Dp, Elevation, MaybeVar, Opacity, Outline, ShapeRadii, TextStyle, Ui, Vars } from "@internal/prelude";

export interface Filter {
  readonly outlineWidthUnselected: Dp,
  readonly outlineWidthSelected: Dp,

  readonly outlineColorDisabledUnselected: MaybeVar<Color>,
  readonly outlineColorUnselected: MaybeVar<Color>,
  readonly outlineColorUnselectedFocused: MaybeVar<Color>,
  readonly outlineColorSelected: MaybeVar<Color>,

  readonly outlineOpacityDisabledUnselected: MaybeVar<Opacity>,

  readonly containerShape: MaybeVar<ShapeRadii>,
  readonly containerHeight: Dp,

  readonly containerElevation: MaybeVar<Elevation>,
  readonly containerElevationDragged: MaybeVar<Elevation>,
  readonly containerElevationElevated: MaybeVar<Elevation>,
  readonly containerElevationElevatedDisabled: MaybeVar<Elevation>,
  readonly containerElevationElevatedFocused: MaybeVar<Elevation>,
  readonly containerElevationElevatedHovered: MaybeVar<Elevation>,
  readonly containerElevationElevatedPressed: MaybeVar<Elevation>,
  readonly containerElevationUnselectedFocused: MaybeVar<Elevation>,
  readonly containerElevationUnselectedHovered: MaybeVar<Elevation>,
  readonly containerElevationUnselectedPressed: MaybeVar<Elevation>,
  readonly containerElevationSelectedFocused: MaybeVar<Elevation>,
  readonly containerElevationSelectedHovered: MaybeVar<Elevation>,
  readonly containerElevationSelectedPressed: MaybeVar<Elevation>,

  readonly containerShadowColor: MaybeVar<Color>,
  readonly containerShadowColorElevated: MaybeVar<Color>,

  readonly containerColorDisabledSelected: MaybeVar<Color>,
  readonly containerColorElevatedDisabled: MaybeVar<Color>,
  readonly containerColorElevatedUnselected: MaybeVar<Color>,
  readonly containerColorElevatedSelected: MaybeVar<Color>,

  readonly containerOpacityDisabledSelected: MaybeVar<Opacity>,
  readonly containerOpacityElevatedDisabled: MaybeVar<Opacity>,

  readonly labelStyle: MaybeVar<TextStyle>,

  readonly labelColorUnselected: MaybeVar<Color>,
  readonly labelColorUnselectedFocused: MaybeVar<Color>,
  readonly labelColorUnselectedHovered: MaybeVar<Color>,
  readonly labelColorUnselectedPressed: MaybeVar<Color>,
  readonly labelColorUnselectedDragged: MaybeVar<Color>,
  readonly labelColorSelected: MaybeVar<Color>,
  readonly labelColorDisabled: MaybeVar<Color>,
  readonly labelColorSelectedFocused: MaybeVar<Color>,
  readonly labelColorSelectedHovered: MaybeVar<Color>,
  readonly labelColorSelectedPressed: MaybeVar<Color>,
  readonly labelColorSelectedDragged: MaybeVar<Color>,

  readonly labelOpacityDisabled: MaybeVar<Opacity>,

  readonly iconSize: Dp,

  readonly iconColorLeadingDisabled: MaybeVar<Color>,
  readonly iconColorLeadingUnselected: MaybeVar<Color>,
  readonly iconColorLeadingUnselectedFocused: MaybeVar<Color>,
  readonly iconColorLeadingUnselectedHovered: MaybeVar<Color>,
  readonly iconColorLeadingUnselectedPressed: MaybeVar<Color>,
  readonly iconColorLeadingUnselectedDragged: MaybeVar<Color>,
  readonly iconColorLeadingSelected: MaybeVar<Color>,
  readonly iconColorLeadingSelectedFocused: MaybeVar<Color>,
  readonly iconColorLeadingSelectedHovered: MaybeVar<Color>,
  readonly iconColorLeadingSelectedPressed: MaybeVar<Color>,
  readonly iconColorLeadingSelectedDragged: MaybeVar<Color>,
  readonly iconColorTrailingDisabled: MaybeVar<Color>,
  readonly iconColorTrailingUnselected: MaybeVar<Color>,
  readonly iconColorTrailingUnselectedFocused: MaybeVar<Color>,
  readonly iconColorTrailingUnselectedHovered: MaybeVar<Color>,
  readonly iconColorTrailingUnselectedPressed: MaybeVar<Color>,
  readonly iconColorTrailingUnselectedDragged: MaybeVar<Color>,
  readonly iconColorTrailingSelected: MaybeVar<Color>,
  readonly iconColorTrailingSelectedFocused: MaybeVar<Color>,
  readonly iconColorTrailingSelectedHovered: MaybeVar<Color>,
  readonly iconColorTrailingSelectedPressed: MaybeVar<Color>,
  readonly iconColorTrailingSelectedDragged: MaybeVar<Color>,

  readonly iconOpacityLeadingDisabled: MaybeVar<Opacity>,
  readonly iconOpacityTrailingDisabled: MaybeVar<Opacity>,

  readonly focusIndicator: MaybeVar<Outline>,

  readonly stateLayerColorUnselectedFocused: MaybeVar<Color>,
  readonly stateLayerColorUnselectedHovered: MaybeVar<Color>,
  readonly stateLayerColorUnselectedPressed: MaybeVar<Color>,
  readonly stateLayerColorUnselectedDragged: MaybeVar<Color>,
  readonly stateLayerColorSelectedFocused: MaybeVar<Color>,
  readonly stateLayerColorSelectedHovered: MaybeVar<Color>,
  readonly stateLayerColorSelectedPressed: MaybeVar<Color>,
  readonly stateLayerColorSelectedDragged: MaybeVar<Color>,

  readonly stateLayerOpacityUnselectedFocused: MaybeVar<Opacity>,
  readonly stateLayerOpacityUnselectedHovered: MaybeVar<Opacity>,
  readonly stateLayerOpacityUnselectedPressed: MaybeVar<Opacity>,
  readonly stateLayerOpacityUnselectedDragged: MaybeVar<Opacity>,
  readonly stateLayerOpacitySelectedFocused: MaybeVar<Opacity>,
  readonly stateLayerOpacitySelectedHovered: MaybeVar<Opacity>,
  readonly stateLayerOpacitySelectedPressed: MaybeVar<Opacity>,
  readonly stateLayerOpacitySelectedDragged: MaybeVar<Opacity>,
}

export const Filter = (): Filter => ({
  outlineWidthUnselected: Dp.create(1),
  outlineWidthSelected: Dp.create(0),

  outlineColorDisabledUnselected: Vars.ColorScheme.OnSurface(),
  outlineColorUnselected: Vars.ColorScheme.OutlineVariant(),
  outlineColorUnselectedFocused: Vars.ColorScheme.OnSurfaceVariant(),
  outlineColorSelected: Vars.ColorScheme.SecondaryContainer(),

  outlineOpacityDisabledUnselected: Ui.create(0.12),

  containerShape: Vars.ShapeScheme.Small(),
  containerHeight: Dp.create(32),

  containerElevation: Vars.ElevationScheme.Level0(),
  containerElevationDragged: Vars.ElevationScheme.Level4(),
  containerElevationElevated: Vars.ElevationScheme.Level1(),
  containerElevationElevatedDisabled: Vars.ElevationScheme.Level0(),
  containerElevationElevatedFocused: Vars.ElevationScheme.Level1(),
  containerElevationElevatedHovered: Vars.ElevationScheme.Level2(),
  containerElevationElevatedPressed: Vars.ElevationScheme.Level1(),
  containerElevationUnselectedFocused: Vars.ElevationScheme.Level0(),
  containerElevationUnselectedHovered: Vars.ElevationScheme.Level0(),
  containerElevationUnselectedPressed: Vars.ElevationScheme.Level0(),
  containerElevationSelectedFocused: Vars.ElevationScheme.Level0(),
  containerElevationSelectedHovered: Vars.ElevationScheme.Level1(),
  containerElevationSelectedPressed: Vars.ElevationScheme.Level0(),

  containerShadowColor: Vars.ColorScheme.Shadow(),
  containerShadowColorElevated: Vars.ColorScheme.Shadow(),

  containerColorDisabledSelected: Vars.ColorScheme.OnSurface(),
  containerColorElevatedDisabled: Vars.ColorScheme.OnSurface(),
  containerColorElevatedUnselected: Vars.ColorScheme.SurfaceContainerLow(),
  containerColorElevatedSelected: Vars.ColorScheme.SecondaryContainer(),

  containerOpacityDisabledSelected: Ui.create(0.12),
  containerOpacityElevatedDisabled: Ui.create(0.12),

  labelStyle: Vars.Typescale.LabelLarge(),

  labelColorUnselected: Vars.ColorScheme.OnSurfaceVariant(),
  labelColorUnselectedFocused: Vars.ColorScheme.OnSurfaceVariant(),
  labelColorUnselectedHovered: Vars.ColorScheme.OnSurfaceVariant(),
  labelColorUnselectedPressed: Vars.ColorScheme.OnSurfaceVariant(),
  labelColorUnselectedDragged: Vars.ColorScheme.OnSurfaceVariant(),
  labelColorSelected: Vars.ColorScheme.OnSecondaryContainer(),
  labelColorDisabled: Vars.ColorScheme.OnSurface(),
  labelColorSelectedFocused: Vars.ColorScheme.OnSecondaryContainer(),
  labelColorSelectedHovered: Vars.ColorScheme.OnSecondaryContainer(),
  labelColorSelectedPressed: Vars.ColorScheme.OnSecondaryContainer(),
  labelColorSelectedDragged: Vars.ColorScheme.OnSecondaryContainer(),

  labelOpacityDisabled: Ui.create(0.38),

  iconSize: Dp.create(18),

  iconColorLeadingDisabled: Vars.ColorScheme.OnSurface(),
  iconColorLeadingUnselected: Vars.ColorScheme.Primary(),
  iconColorLeadingUnselectedFocused: Vars.ColorScheme.Primary(),
  iconColorLeadingUnselectedHovered: Vars.ColorScheme.Primary(),
  iconColorLeadingUnselectedPressed: Vars.ColorScheme.Primary(),
  iconColorLeadingUnselectedDragged: Vars.ColorScheme.Primary(),
  iconColorLeadingSelected: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorLeadingSelectedFocused: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorLeadingSelectedHovered: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorLeadingSelectedPressed: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorLeadingSelectedDragged: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorTrailingDisabled: Vars.ColorScheme.OnSurface(),
  iconColorTrailingUnselected: Vars.ColorScheme.OnSurfaceVariant(),
  iconColorTrailingUnselectedFocused: Vars.ColorScheme.OnSurfaceVariant(),
  iconColorTrailingUnselectedHovered: Vars.ColorScheme.OnSurfaceVariant(),
  iconColorTrailingUnselectedPressed: Vars.ColorScheme.OnSurfaceVariant(),
  iconColorTrailingUnselectedDragged: Vars.ColorScheme.OnSurfaceVariant(),
  iconColorTrailingSelected: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorTrailingSelectedFocused: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorTrailingSelectedHovered: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorTrailingSelectedPressed: Vars.ColorScheme.OnSecondaryContainer(),
  iconColorTrailingSelectedDragged: Vars.ColorScheme.OnSecondaryContainer(),

  iconOpacityLeadingDisabled: Ui.create(0.38),
  iconOpacityTrailingDisabled: Ui.create(0.38),

  focusIndicator: Outline.create({
    color: Vars.ColorScheme.Secondary(),
    offset: Vars.FocusIndicator.OuterOffset(),
    thickness: Vars.FocusIndicator.Thickness(),
  }),

  stateLayerColorUnselectedFocused: Vars.ColorScheme.OnSurfaceVariant(),
  stateLayerColorUnselectedHovered: Vars.ColorScheme.OnSurfaceVariant(),
  stateLayerColorUnselectedPressed: Vars.ColorScheme.OnSecondaryContainer(),
  stateLayerColorUnselectedDragged: Vars.ColorScheme.OnSurfaceVariant(),
  stateLayerColorSelectedFocused: Vars.ColorScheme.OnSecondaryContainer(),
  stateLayerColorSelectedHovered: Vars.ColorScheme.OnSecondaryContainer(),
  stateLayerColorSelectedPressed: Vars.ColorScheme.OnSurfaceVariant(),
  stateLayerColorSelectedDragged: Vars.ColorScheme.OnSecondaryContainer(),

  stateLayerOpacityUnselectedFocused: Vars.Opacities.Focused(),
  stateLayerOpacityUnselectedHovered: Vars.Opacities.Hovered(),
  stateLayerOpacityUnselectedPressed: Vars.Opacities.Pressed(),
  stateLayerOpacityUnselectedDragged: Vars.Opacities.Dragged(),
  stateLayerOpacitySelectedFocused: Vars.Opacities.Focused(),
  stateLayerOpacitySelectedHovered: Vars.Opacities.Hovered(),
  stateLayerOpacitySelectedPressed: Vars.Opacities.Pressed(),
  stateLayerOpacitySelectedDragged: Vars.Opacities.Dragged(),
});