import { Vars, MaybeVar, Color, Dp, ShapeRadii, ShapesRef, TextStyle, TypescaleRef, Ui, AsymmetricCornerRadius } from "@internal/prelude";

// TODO: Split individual component styles

export interface SliderStyle {
  readonly stopIndicatorSize: Dp,
  readonly stopIndicatorShape: MaybeVar<ShapeRadii>,
  readonly stopIndicatorTrailingSpace: Dp,
  readonly stopIndicatorColor: MaybeVar<Color>,
  readonly stopIndicatorColorSelected: MaybeVar<Color>,
  readonly activeStopIndicatorContainerColor: MaybeVar<Color>,
  readonly activeStopIndicatorContainerOpacity: MaybeVar<Opacity>
  readonly inactiveStopIndicatorContainerColor: MaybeVar<Color>,
  readonly inactiveStopIndicatorContainerOpacity: MaybeVar<Opacity>
  readonly activeTrackHeight: Dp,
  readonly inactiveTrackHeight: Dp,
  readonly activeTrackShape: MaybeVar<ShapeRadii>,
  readonly activeTrackOuterCornerSize: MaybeVar<ShapeRadii>,
  readonly activeTrackInnerCornerSize: AsymmetricCornerRadius,
  readonly inactiveTrackShape: MaybeVar<ShapeRadii>,
  readonly activeTrackColor: MaybeVar<Color>,
  readonly inactiveTrackColor: MaybeVar<Color>,
  readonly handleHeight: Dp,
  readonly handleWidth: Dp,
  readonly handleShape: MaybeVar<ShapeRadii>,
  readonly handleColor: MaybeVar<Color>,
  readonly activeHandleColor: MaybeVar<Color>,
  readonly activeHandleHeight: Dp,
  readonly activeHandleWidth: Dp,
  readonly activeHandleShape: MaybeVar<ShapeRadii>,
  readonly activeHandleLeadingSpace: Dp,
  readonly activeHandleTrailingSpace: Dp,
  readonly activeHandlePadding: Dp,
  readonly disabledActiveStopIndicatorContainerColor: MaybeVar<Color>,
  readonly disabledInactiveStopIndicatorContainerColor: MaybeVar<Color>,
  readonly disabledActiveTrackColor: MaybeVar<Color>,
  readonly disabledActiveTrackOpacity: MaybeVar<Opacity>
  readonly disabledInactiveTrackColor: MaybeVar<Color>,
  readonly disabledInactiveTrackOpacity: MaybeVar<Opacity>
  readonly disabledHandleColor: MaybeVar<Color>,
  readonly disabledHandleOpacity: MaybeVar<Opacity>
  readonly disabledHandleWidth: Dp,
  readonly hoverHandleWidth: Dp,
  readonly focusActiveTrackColor: MaybeVar<Color>,
  readonly focusInactiveTrackColor: MaybeVar<Color>,
  readonly focusHandleWidth: Dp,
  readonly pressedHandleColor: MaybeVar<Color>,
  readonly pressedHandleWidth: Dp,
  readonly pressedActiveTrackColor: MaybeVar<Color>,
  readonly pressedInactiveTrackColor: MaybeVar<Color>,
  readonly valueIndicatorContainerColor: MaybeVar<Color>,
  readonly valueIndicatorLabelStyle: MaybeVar<TextStyle>,
  readonly valueIndicatorActiveBottomSpace: Dp,
}

export const create = (): SliderStyle => {
  return {
    stopIndicatorSize: Dp.create(4),
    stopIndicatorShape: Vars.ShapeScheme.Full(),
    stopIndicatorTrailingSpace: Dp.create(4),
    stopIndicatorColor: Vars.ColorScheme.OnSecondaryContainer(),
    stopIndicatorColorSelected: Vars.ColorScheme.OnPrimary(),
    activeStopIndicatorContainerColor: Vars.ColorScheme.OnPrimary(),
    activeStopIndicatorContainerOpacity: Ui.create(1),
    inactiveStopIndicatorContainerColor: Vars.ColorScheme.OnSecondaryContainer(),
    inactiveStopIndicatorContainerOpacity: Ui.create(1),
    activeTrackHeight: Dp.create(16),
    inactiveTrackHeight: Dp.create(16),
    activeTrackShape: Vars.ShapeScheme.Full(),
    activeTrackOuterCornerSize: Vars.ShapeScheme.Full(),
    activeTrackInnerCornerSize: AsymmetricCornerRadius.create({
      vertical: Dp.create(2), horizontal: Dp.create(2) 
    }),
    inactiveTrackShape: Vars.ShapeScheme.Full(),
    activeTrackColor: Vars.ColorScheme.Primary(),
    inactiveTrackColor: Vars.ColorScheme.SecondaryContainer(),
    handleHeight: Dp.create(44),
    handleWidth: Dp.create(4),
    handleShape: Vars.ShapeScheme.Full(),
    handleColor: Vars.ColorScheme.Primary(),
    activeHandleColor: Vars.ColorScheme.Primary(),
    activeHandleHeight: Dp.create(44),
    activeHandleWidth: Dp.create(4),
    activeHandleShape: Vars.ShapeScheme.Full(),
    activeHandleLeadingSpace: Dp.create(6),
    activeHandleTrailingSpace: Dp.create(6),
    activeHandlePadding: Dp.create(6),
    disabledActiveStopIndicatorContainerColor: Vars.ColorScheme.InverseOnSurface(),
    disabledInactiveStopIndicatorContainerColor: Vars.ColorScheme.OnSurface(),
    disabledActiveTrackColor: Vars.ColorScheme.OnSurface(),
    disabledActiveTrackOpacity: Ui.create(0.38),
    disabledInactiveTrackColor: Vars.ColorScheme.OnSurface(),
    disabledInactiveTrackOpacity: Ui.create(0.12),
    disabledHandleColor: Vars.ColorScheme.OnSurface(),
    disabledHandleOpacity: Ui.create(0.38),
    disabledHandleWidth: Dp.create(4),
    hoverHandleWidth: Dp.create(4),
    focusActiveTrackColor: Vars.ColorScheme.Primary(),
    focusInactiveTrackColor: Vars.ColorScheme.SecondaryContainer(),
    focusHandleWidth: Dp.create(2),
    pressedHandleColor: Vars.ColorScheme.Primary(),
    pressedHandleWidth: Dp.create(2),
    pressedActiveTrackColor: Vars.ColorScheme.Primary(),
    pressedInactiveTrackColor: Vars.ColorScheme.SecondaryContainer(),
    valueIndicatorContainerColor: Vars.ColorScheme.InverseSurface(),
    valueIndicatorLabelStyle: Vars.Typescale.LabelLarge(),
    valueIndicatorActiveBottomSpace: Dp.create(12),
  };
};