import { HexColor } from "@internal/prelude";

export interface ColorPalette {
  readonly black: HexColor,
  readonly error0: HexColor,
  readonly error10: HexColor,
  readonly error100: HexColor,
  readonly error20: HexColor,
  readonly error30: HexColor,
  readonly error40: HexColor,
  readonly error50: HexColor,
  readonly error60: HexColor,
  readonly error70: HexColor,
  readonly error80: HexColor,
  readonly error90: HexColor,
  readonly error95: HexColor,
  readonly error99: HexColor,
  readonly neutralVariant0: HexColor,
  readonly neutralVariant10: HexColor,
  readonly neutralVariant100: HexColor,
  readonly neutralVariant20: HexColor,
  readonly neutralVariant30: HexColor,
  readonly neutralVariant40: HexColor,
  readonly neutralVariant50: HexColor,
  readonly neutralVariant60: HexColor,
  readonly neutralVariant70: HexColor,
  readonly neutralVariant80: HexColor,
  readonly neutralVariant90: HexColor,
  readonly neutralVariant95: HexColor,
  readonly neutralVariant99: HexColor,
  readonly neutral0: HexColor,
  readonly neutral10: HexColor,
  readonly neutral100: HexColor,
  readonly neutral12: HexColor,
  readonly neutral17: HexColor,
  readonly neutral20: HexColor,
  readonly neutral22: HexColor,
  readonly neutral24: HexColor,
  readonly neutral30: HexColor,
  readonly neutral4: HexColor,
  readonly neutral40: HexColor,
  readonly neutral50: HexColor,
  readonly neutral6: HexColor,
  readonly neutral60: HexColor,
  readonly neutral70: HexColor,
  readonly neutral80: HexColor,
  readonly neutral87: HexColor,
  readonly neutral90: HexColor,
  readonly neutral92: HexColor,
  readonly neutral94: HexColor,
  readonly neutral95: HexColor,
  readonly neutral96: HexColor,
  readonly neutral98: HexColor,
  readonly neutral99: HexColor,
  readonly primary0: HexColor,
  readonly primary10: HexColor,
  readonly primary100: HexColor,
  readonly primary20: HexColor,
  readonly primary30: HexColor,
  readonly primary40: HexColor,
  readonly primary50: HexColor,
  readonly primary60: HexColor,
  readonly primary70: HexColor,
  readonly primary80: HexColor,
  readonly primary90: HexColor,
  readonly primary95: HexColor,
  readonly primary99: HexColor,
  readonly secondary0: HexColor,
  readonly secondary10: HexColor,
  readonly secondary100: HexColor,
  readonly secondary20: HexColor,
  readonly secondary30: HexColor,
  readonly secondary40: HexColor,
  readonly secondary50: HexColor,
  readonly secondary60: HexColor,
  readonly secondary70: HexColor,
  readonly secondary80: HexColor,
  readonly secondary90: HexColor,
  readonly secondary95: HexColor,
  readonly secondary99: HexColor,
  readonly tertiary0: HexColor,
  readonly tertiary10: HexColor,
  readonly tertiary100: HexColor,
  readonly tertiary20: HexColor,
  readonly tertiary30: HexColor,
  readonly tertiary40: HexColor,
  readonly tertiary50: HexColor,
  readonly tertiary60: HexColor,
  readonly tertiary70: HexColor,
  readonly tertiary80: HexColor,
  readonly tertiary90: HexColor,
  readonly tertiary95: HexColor,
  readonly tertiary99: HexColor,
  readonly white: HexColor,
}

export const baseline = () => ({
  black: HexColor.fromString("#000"),
  error0: HexColor.fromString("#000"),
  error10: HexColor.fromString("#410e0b"),
  error100: HexColor.fromString("#fff"),
  error20: HexColor.fromString("#601410"),
  error30: HexColor.fromString("#8c1d18"),
  error40: HexColor.fromString("#b3261e"),
  error50: HexColor.fromString("#dc362e"),
  error60: HexColor.fromString("#e46962"),
  error70: HexColor.fromString("#ec928e"),
  error80: HexColor.fromString("#f2b8b5"),
  error90: HexColor.fromString("#f9dedc"),
  error95: HexColor.fromString("#fceeee"),
  error99: HexColor.fromString("#fffbf9"),
  neutralVariant0: HexColor.fromString("#000"),
  neutralVariant10: HexColor.fromString("#1d1a22"),
  neutralVariant100: HexColor.fromString("#fff"),
  neutralVariant20: HexColor.fromString("#322f37"),
  neutralVariant30: HexColor.fromString("#49454f"),
  neutralVariant40: HexColor.fromString("#605d66"),
  neutralVariant50: HexColor.fromString("#79747e"),
  neutralVariant60: HexColor.fromString("#938f99"),
  neutralVariant70: HexColor.fromString("#aea9b4"),
  neutralVariant80: HexColor.fromString("#cac4d0"),
  neutralVariant90: HexColor.fromString("#e7e0ec"),
  neutralVariant95: HexColor.fromString("#f5eefa"),
  neutralVariant99: HexColor.fromString("#fffbfe"),
  neutral0: HexColor.fromString("#000"),
  neutral10: HexColor.fromString("#1d1b20"),
  neutral100: HexColor.fromString("#fff"),
  neutral12: HexColor.fromString("#211f26"),
  neutral17: HexColor.fromString("#2b2930"),
  neutral20: HexColor.fromString("#322f35"),
  neutral22: HexColor.fromString("#36343b"),
  neutral24: HexColor.fromString("#3b383e"),
  neutral30: HexColor.fromString("#48464c"),
  neutral4: HexColor.fromString("#0f0d13"),
  neutral40: HexColor.fromString("#605d64"),
  neutral50: HexColor.fromString("#79767d"),
  neutral6: HexColor.fromString("#141218"),
  neutral60: HexColor.fromString("#938f96"),
  neutral70: HexColor.fromString("#aea9b1"),
  neutral80: HexColor.fromString("#cac5cd"),
  neutral87: HexColor.fromString("#ded8e1"),
  neutral90: HexColor.fromString("#e6e0e9"),
  neutral92: HexColor.fromString("#ece6f0"),
  neutral94: HexColor.fromString("#f3edf7"),
  neutral95: HexColor.fromString("#f5eff7"),
  neutral96: HexColor.fromString("#f7f2fa"),
  neutral98: HexColor.fromString("#fef7ff"),
  neutral99: HexColor.fromString("#fffbff"),
  primary0: HexColor.fromString("#000"),
  primary10: HexColor.fromString("#21005d"),
  primary100: HexColor.fromString("#fff"),
  primary20: HexColor.fromString("#381e72"),
  primary30: HexColor.fromString("#4f378b"),
  primary40: HexColor.fromString("#6750a4"),
  primary50: HexColor.fromString("#7f67be"),
  primary60: HexColor.fromString("#9a82db"),
  primary70: HexColor.fromString("#b69df8"),
  primary80: HexColor.fromString("#d0bcff"),
  primary90: HexColor.fromString("#eaddff"),
  primary95: HexColor.fromString("#f6edff"),
  primary99: HexColor.fromString("#fffbfe"),
  secondary0: HexColor.fromString("#000"),
  secondary10: HexColor.fromString("#1d192b"),
  secondary100: HexColor.fromString("#fff"),
  secondary20: HexColor.fromString("#332d41"),
  secondary30: HexColor.fromString("#4a4458"),
  secondary40: HexColor.fromString("#625b71"),
  secondary50: HexColor.fromString("#7a7289"),
  secondary60: HexColor.fromString("#958da5"),
  secondary70: HexColor.fromString("#b0a7c0"),
  secondary80: HexColor.fromString("#ccc2dc"),
  secondary90: HexColor.fromString("#e8def8"),
  secondary95: HexColor.fromString("#f6edff"),
  secondary99: HexColor.fromString("#fffbfe"),
  tertiary0: HexColor.fromString("#000"),
  tertiary10: HexColor.fromString("#31111d"),
  tertiary100: HexColor.fromString("#fff"),
  tertiary20: HexColor.fromString("#492532"),
  tertiary30: HexColor.fromString("#633b48"),
  tertiary40: HexColor.fromString("#7d5260"),
  tertiary50: HexColor.fromString("#986977"),
  tertiary60: HexColor.fromString("#b58392"),
  tertiary70: HexColor.fromString("#d29dac"),
  tertiary80: HexColor.fromString("#efb8c8"),
  tertiary90: HexColor.fromString("#ffd8e4"),
  tertiary95: HexColor.fromString("#ffecf1"),
  tertiary99: HexColor.fromString("#fffbfa"),
  white: HexColor.fromString("#fff"),
});

export const ColorPalette = {
  baseline,
};