import { Var } from "./Var.ts";
import { Color } from "@internal/prelude";

const _Black = null as unknown as Var<Color>;
const _Error0 = null as unknown as Var<Color>;
const _Error10 = null as unknown as Var<Color>;
const _Error100 = null as unknown as Var<Color>;
const _Error20 = null as unknown as Var<Color>;
const _Error30 = null as unknown as Var<Color>;
const _Error40 = null as unknown as Var<Color>;
const _Error50 = null as unknown as Var<Color>;
const _Error60 = null as unknown as Var<Color>;
const _Error70 = null as unknown as Var<Color>;
const _Error80 = null as unknown as Var<Color>;
const _Error90 = null as unknown as Var<Color>;
const _Error95 = null as unknown as Var<Color>;
const _Error99 = null as unknown as Var<Color>;
const _NeutralVariant0 = null as unknown as Var<Color>;
const _NeutralVariant10 = null as unknown as Var<Color>;
const _NeutralVariant100 = null as unknown as Var<Color>;
const _NeutralVariant20 = null as unknown as Var<Color>;
const _NeutralVariant30 = null as unknown as Var<Color>;
const _NeutralVariant40 = null as unknown as Var<Color>;
const _NeutralVariant50 = null as unknown as Var<Color>;
const _NeutralVariant60 = null as unknown as Var<Color>;
const _NeutralVariant70 = null as unknown as Var<Color>;
const _NeutralVariant80 = null as unknown as Var<Color>;
const _NeutralVariant90 = null as unknown as Var<Color>;
const _NeutralVariant95 = null as unknown as Var<Color>;
const _NeutralVariant99 = null as unknown as Var<Color>;
const _Neutral0 = null as unknown as Var<Color>;
const _Neutral10 = null as unknown as Var<Color>;
const _Neutral100 = null as unknown as Var<Color>;
const _Neutral12 = null as unknown as Var<Color>;
const _Neutral17 = null as unknown as Var<Color>;
const _Neutral20 = null as unknown as Var<Color>;
const _Neutral22 = null as unknown as Var<Color>;
const _Neutral24 = null as unknown as Var<Color>;
const _Neutral30 = null as unknown as Var<Color>;
const _Neutral4 = null as unknown as Var<Color>;
const _Neutral40 = null as unknown as Var<Color>;
const _Neutral50 = null as unknown as Var<Color>;
const _Neutral6 = null as unknown as Var<Color>;
const _Neutral60 = null as unknown as Var<Color>;
const _Neutral70 = null as unknown as Var<Color>;
const _Neutral80 = null as unknown as Var<Color>;
const _Neutral87 = null as unknown as Var<Color>;
const _Neutral90 = null as unknown as Var<Color>;
const _Neutral92 = null as unknown as Var<Color>;
const _Neutral94 = null as unknown as Var<Color>;
const _Neutral95 = null as unknown as Var<Color>;
const _Neutral96 = null as unknown as Var<Color>;
const _Neutral98 = null as unknown as Var<Color>;
const _Neutral99 = null as unknown as Var<Color>;
const _Primary0 = null as unknown as Var<Color>;
const _Primary10 = null as unknown as Var<Color>;
const _Primary100 = null as unknown as Var<Color>;
const _Primary20 = null as unknown as Var<Color>;
const _Primary30 = null as unknown as Var<Color>;
const _Primary40 = null as unknown as Var<Color>;
const _Primary50 = null as unknown as Var<Color>;
const _Primary60 = null as unknown as Var<Color>;
const _Primary70 = null as unknown as Var<Color>;
const _Primary80 = null as unknown as Var<Color>;
const _Primary90 = null as unknown as Var<Color>;
const _Primary95 = null as unknown as Var<Color>;
const _Primary99 = null as unknown as Var<Color>;
const _Secondary0 = null as unknown as Var<Color>;
const _Secondary10 = null as unknown as Var<Color>;
const _Secondary100 = null as unknown as Var<Color>;
const _Secondary20 = null as unknown as Var<Color>;
const _Secondary30 = null as unknown as Var<Color>;
const _Secondary40 = null as unknown as Var<Color>;
const _Secondary50 = null as unknown as Var<Color>;
const _Secondary60 = null as unknown as Var<Color>;
const _Secondary70 = null as unknown as Var<Color>;
const _Secondary80 = null as unknown as Var<Color>;
const _Secondary90 = null as unknown as Var<Color>;
const _Secondary95 = null as unknown as Var<Color>;
const _Secondary99 = null as unknown as Var<Color>;
const _Tertiary0 = null as unknown as Var<Color>;
const _Tertiary10 = null as unknown as Var<Color>;
const _Tertiary100 = null as unknown as Var<Color>;
const _Tertiary20 = null as unknown as Var<Color>;
const _Tertiary30 = null as unknown as Var<Color>;
const _Tertiary40 = null as unknown as Var<Color>;
const _Tertiary50 = null as unknown as Var<Color>;
const _Tertiary60 = null as unknown as Var<Color>;
const _Tertiary70 = null as unknown as Var<Color>;
const _Tertiary80 = null as unknown as Var<Color>;
const _Tertiary90 = null as unknown as Var<Color>;
const _Tertiary95 = null as unknown as Var<Color>;
const _Tertiary99 = null as unknown as Var<Color>;
const _White = null as unknown as Var<Color>;


export const Black = () => _Black;
export const Error0 = () => _Error0;
export const Error10 = () => _Error10;
export const Error100 = () => _Error100;
export const Error20 = () => _Error20;
export const Error30 = () => _Error30;
export const Error40 = () => _Error40;
export const Error50 = () => _Error50;
export const Error60 = () => _Error60;
export const Error70 = () => _Error70;
export const Error80 = () => _Error80;
export const Error90 = () => _Error90;
export const Error95 = () => _Error95;
export const Error99 = () => _Error99;
export const NeutralVariant0 = () => _NeutralVariant0;
export const NeutralVariant10 = () => _NeutralVariant10;
export const NeutralVariant100 = () => _NeutralVariant100;
export const NeutralVariant20 = () => _NeutralVariant20;
export const NeutralVariant30 = () => _NeutralVariant30;
export const NeutralVariant40 = () => _NeutralVariant40;
export const NeutralVariant50 = () => _NeutralVariant50;
export const NeutralVariant60 = () => _NeutralVariant60;
export const NeutralVariant70 = () => _NeutralVariant70;
export const NeutralVariant80 = () => _NeutralVariant80;
export const NeutralVariant90 = () => _NeutralVariant90;
export const NeutralVariant95 = () => _NeutralVariant95;
export const NeutralVariant99 = () => _NeutralVariant99;
export const Neutral0 = () => _Neutral0;
export const Neutral10 = () => _Neutral10;
export const Neutral100 = () => _Neutral100;
export const Neutral12 = () => _Neutral12;
export const Neutral17 = () => _Neutral17;
export const Neutral20 = () => _Neutral20;
export const Neutral22 = () => _Neutral22;
export const Neutral24 = () => _Neutral24;
export const Neutral30 = () => _Neutral30;
export const Neutral4 = () => _Neutral4;
export const Neutral40 = () => _Neutral40;
export const Neutral50 = () => _Neutral50;
export const Neutral6 = () => _Neutral6;
export const Neutral60 = () => _Neutral60;
export const Neutral70 = () => _Neutral70;
export const Neutral80 = () => _Neutral80;
export const Neutral87 = () => _Neutral87;
export const Neutral90 = () => _Neutral90;
export const Neutral92 = () => _Neutral92;
export const Neutral94 = () => _Neutral94;
export const Neutral95 = () => _Neutral95;
export const Neutral96 = () => _Neutral96;
export const Neutral98 = () => _Neutral98;
export const Neutral99 = () => _Neutral99;
export const Primary0 = () => _Primary0;
export const Primary10 = () => _Primary10;
export const Primary100 = () => _Primary100;
export const Primary20 = () => _Primary20;
export const Primary30 = () => _Primary30;
export const Primary40 = () => _Primary40;
export const Primary50 = () => _Primary50;
export const Primary60 = () => _Primary60;
export const Primary70 = () => _Primary70;
export const Primary80 = () => _Primary80;
export const Primary90 = () => _Primary90;
export const Primary95 = () => _Primary95;
export const Primary99 = () => _Primary99;
export const Secondary0 = () => _Secondary0;
export const Secondary10 = () => _Secondary10;
export const Secondary100 = () => _Secondary100;
export const Secondary20 = () => _Secondary20;
export const Secondary30 = () => _Secondary30;
export const Secondary40 = () => _Secondary40;
export const Secondary50 = () => _Secondary50;
export const Secondary60 = () => _Secondary60;
export const Secondary70 = () => _Secondary70;
export const Secondary80 = () => _Secondary80;
export const Secondary90 = () => _Secondary90;
export const Secondary95 = () => _Secondary95;
export const Secondary99 = () => _Secondary99;
export const Tertiary0 = () => _Tertiary0;
export const Tertiary10 = () => _Tertiary10;
export const Tertiary100 = () => _Tertiary100;
export const Tertiary20 = () => _Tertiary20;
export const Tertiary30 = () => _Tertiary30;
export const Tertiary40 = () => _Tertiary40;
export const Tertiary50 = () => _Tertiary50;
export const Tertiary60 = () => _Tertiary60;
export const Tertiary70 = () => _Tertiary70;
export const Tertiary80 = () => _Tertiary80;
export const Tertiary90 = () => _Tertiary90;
export const Tertiary95 = () => _Tertiary95;
export const Tertiary99 = () => _Tertiary99;
export const White = () => _White;