import { Color } from "@internal/prelude";
import { Var } from "./Var.ts";

const _Background = null as unknown as Var<Color>;
const _Error = null as unknown as Var<Color>;
const _ErrorContainer = null as unknown as Var<Color>;
const _InverseOnSurface = null as unknown as Var<Color>;
const _InversePrimary = null as unknown as Var<Color>;
const _InverseSurface = null as unknown as Var<Color>;
const _OnBackground = null as unknown as Var<Color>;
const _OnError = null as unknown as Var<Color>;
const _OnErrorContainer = null as unknown as Var<Color>;
const _OnPrimary = null as unknown as Var<Color>;
const _OnPrimaryContainer = null as unknown as Var<Color>;
const _OnPrimaryFixed = null as unknown as Var<Color>;
const _OnPrimaryFixedVariant = null as unknown as Var<Color>;
const _OnSecondary = null as unknown as Var<Color>;
const _OnSecondaryContainer = null as unknown as Var<Color>;
const _OnSecondaryFixed = null as unknown as Var<Color>;
const _OnSecondaryFixedVariant = null as unknown as Var<Color>;
const _OnSurface = null as unknown as Var<Color>;
const _OnSurfaceVariant = null as unknown as Var<Color>;
const _OnTertiary = null as unknown as Var<Color>;
const _OnTertiaryContainer = null as unknown as Var<Color>;
const _OnTertiaryFixed = null as unknown as Var<Color>;
const _OnTertiaryFixedVariant = null as unknown as Var<Color>;
const _Outline = null as unknown as Var<Color>;
const _OutlineVariant = null as unknown as Var<Color>;
const _Primary = null as unknown as Var<Color>;
const _PrimaryContainer = null as unknown as Var<Color>;
const _PrimaryFixed = null as unknown as Var<Color>;
const _PrimaryFixedDim = null as unknown as Var<Color>;
const _Scrim = null as unknown as Var<Color>;
const _Secondary = null as unknown as Var<Color>;
const _SecondaryContainer = null as unknown as Var<Color>;
const _SecondaryFixed = null as unknown as Var<Color>;
const _SecondaryFixedDim = null as unknown as Var<Color>;
const _Shadow = null as unknown as Var<Color>;
const _Surface = null as unknown as Var<Color>;
const _SurfaceBright = null as unknown as Var<Color>;
const _SurfaceContainer = null as unknown as Var<Color>;
const _SurfaceContainerHigh = null as unknown as Var<Color>;
const _SurfaceContainerHighest = null as unknown as Var<Color>;
const _SurfaceContainerLow = null as unknown as Var<Color>;
const _SurfaceContainerLowest = null as unknown as Var<Color>;
const _SurfaceDim = null as unknown as Var<Color>;
const _SurfaceTint = null as unknown as Var<Color>;
const _SurfaceVariant = null as unknown as Var<Color>;
const _Tertiary = null as unknown as Var<Color>;
const _TertiaryContainer = null as unknown as Var<Color>;
const _TertiaryFixed = null as unknown as Var<Color>;
const _TertiaryFixedDim = null as unknown as Var<Color>;

export const Background = () => _Background;
export const Error = () => _Error;
export const ErrorContainer = () => _ErrorContainer;
export const InverseOnSurface = () => _InverseOnSurface;
export const InversePrimary = () => _InversePrimary;
export const InverseSurface = () => _InverseSurface;
export const OnBackground = () => _OnBackground;
export const OnError = () => _OnError;
export const OnErrorContainer = () => _OnErrorContainer;
export const OnPrimary = () => _OnPrimary;
export const OnPrimaryContainer = () => _OnPrimaryContainer;
export const OnPrimaryFixed = () => _OnPrimaryFixed;
export const OnPrimaryFixedVariant = () => _OnPrimaryFixedVariant;
export const OnSecondary = () => _OnSecondary;
export const OnSecondaryContainer = () => _OnSecondaryContainer;
export const OnSecondaryFixed = () => _OnSecondaryFixed;
export const OnSecondaryFixedVariant = () => _OnSecondaryFixedVariant;
export const OnSurface = () => _OnSurface;
export const OnSurfaceVariant = () => _OnSurfaceVariant;
export const OnTertiary = () => _OnTertiary;
export const OnTertiaryContainer = () => _OnTertiaryContainer;
export const OnTertiaryFixed = () => _OnTertiaryFixed;
export const OnTertiaryFixedVariant = () => _OnTertiaryFixedVariant;
export const Outline = () => _Outline;
export const OutlineVariant = () => _OutlineVariant;
export const Primary = () => _Primary;
export const PrimaryContainer = () => _PrimaryContainer;
export const PrimaryFixed = () => _PrimaryFixed;
export const PrimaryFixedDim = () => _PrimaryFixedDim;
export const Scrim = () => _Scrim;
export const Secondary = () => _Secondary;
export const SecondaryContainer = () => _SecondaryContainer;
export const SecondaryFixed = () => _SecondaryFixed;
export const SecondaryFixedDim = () => _SecondaryFixedDim;
export const Shadow = () => _Shadow;
export const Surface = () => _Surface;
export const SurfaceBright = () => _SurfaceBright;
export const SurfaceContainer = () => _SurfaceContainer;
export const SurfaceContainerHigh = () => _SurfaceContainerHigh;
export const SurfaceContainerHighest = () => _SurfaceContainerHighest;
export const SurfaceContainerLow = () => _SurfaceContainerLow;
export const SurfaceContainerLowest = () => _SurfaceContainerLowest;
export const SurfaceDim = () => _SurfaceDim;
export const SurfaceTint = () => _SurfaceTint;
export const SurfaceVariant = () => _SurfaceVariant;
export const Tertiary = () => _Tertiary;
export const TertiaryContainer = () => _TertiaryContainer;
export const TertiaryFixed = () => _TertiaryFixed;
export const TertiaryFixedDim = () => _TertiaryFixedDim;
