import { CurveCategory, CurveScheme, Curve, Duration, Easing } from "@internal/prelude";
import { Var } from "./Var.ts";

const _Expressive = null as unknown as Var<CurveScheme>;
const _ExpressiveSpatial = null as unknown as Var<CurveCategory>;
const _ExpressiveSpatialFast = null as unknown as Var<Curve>;
const _ExpressiveSpatialFastEasing = null as unknown as Var<Easing>;
const _ExpressiveSpatialFastDuration = null as unknown as Var<Duration>;
const _ExpressiveSpatialDefault = null as unknown as Var<Curve>;
const _ExpressiveSpatialDefaultEasing = null as unknown as Var<Easing>;
const _ExpressiveSpatialDefaultDuration = null as unknown as Var<Duration>;
const _ExpressiveSpatialSlow = null as unknown as Var<Curve>;
const _ExpressiveSpatialSlowEasing = null as unknown as Var<Easing>;
const _ExpressiveSpatialSlowDuration = null as unknown as Var<Duration>;
const _ExpressiveEffects = null as unknown as Var<Curve>;
const _ExpressiveEffectsFast = null as unknown as Var<Curve>;
const _ExpressiveEffectsFastEasing = null as unknown as Var<Easing>;
const _ExpressiveEffectsFastDuration = null as unknown as Var<Duration>;
const _ExpressiveEffectsDefault = null as unknown as Var<Curve>;
const _ExpressiveEffectsDefaultEasing = null as unknown as Var<Easing>;
const _ExpressiveEffectsDefaultDuration = null as unknown as Var<Duration>;
const _ExpressiveEffectsSlow = null as unknown as Var<Curve>;
const _ExpressiveEffectsSlowEasing = null as unknown as Var<Easing>;
const _ExpressiveEffectsSlowDuration = null as unknown as Var<Duration>;
const _Standard = null as unknown as Var<CurveScheme>;
const _StandardSpatial = null as unknown as Var<CurveCategory>;
const _StandardSpatialFast = null as unknown as Var<Curve>;
const _StandardSpatialFastEasing = null as unknown as Var<Easing>;
const _StandardSpatialFastDuration = null as unknown as Var<Duration>;
const _StandardSpatialDefault = null as unknown as Var<Curve>;
const _StandardSpatialDefaultEasing = null as unknown as Var<Easing>;
const _StandardSpatialDefaultDuration = null as unknown as Var<Duration>;
const _StandardSpatialSlow = null as unknown as Var<Curve>;
const _StandardSpatialSlowEasing = null as unknown as Var<Easing>;
const _StandardSpatialSlowDuration = null as unknown as Var<Duration>;
const _StandardEffects = null as unknown as Var<Curve>;
const _StandardEffectsFast = null as unknown as Var<Curve>;
const _StandardEffectsFastEasing = null as unknown as Var<Easing>;
const _StandardEffectsFastDuration = null as unknown as Var<Duration>;
const _StandardEffectsDefault = null as unknown as Var<Curve>;
const _StandardEffectsDefaultEasing = null as unknown as Var<Easing>;
const _StandardEffectsDefaultDuration = null as unknown as Var<Duration>;
const _StandardEffectsSlow = null as unknown as Var<Curve>;
const _StandardEffectsSlowEasing = null as unknown as Var<Easing>;
const _StandardEffectsSlowDuration = null as unknown as Var<Duration>;

export const Expressive = () => _Expressive;
export const ExpressiveSpatial = () => _ExpressiveSpatial;
export const ExpressiveSpatialFast = () => _ExpressiveSpatialFast;
export const ExpressiveSpatialFastEasing = () => _ExpressiveSpatialFastEasing;
export const ExpressiveSpatialFastDuration = () => _ExpressiveSpatialFastDuration;
export const ExpressiveSpatialDefault = () => _ExpressiveSpatialDefault;
export const ExpressiveSpatialDefaultEasing = () => _ExpressiveSpatialDefaultEasing;
export const ExpressiveSpatialDefaultDuration = () => _ExpressiveSpatialDefaultDuration;
export const ExpressiveSpatialSlow = () => _ExpressiveSpatialSlow;
export const ExpressiveSpatialSlowEasing = () => _ExpressiveSpatialSlowEasing;
export const ExpressiveSpatialSlowDuration = () => _ExpressiveSpatialSlowDuration;
export const ExpressiveEffects = () => _ExpressiveEffects;
export const ExpressiveEffectsFast = () => _ExpressiveEffectsFast;
export const ExpressiveEffectsFastEasing = () => _ExpressiveEffectsFastEasing;
export const ExpressiveEffectsFastDuration = () => _ExpressiveEffectsFastDuration;
export const ExpressiveEffectsDefault = () => _ExpressiveEffectsDefault;
export const ExpressiveEffectsDefaultEasing = () => _ExpressiveEffectsDefaultEasing;
export const ExpressiveEffectsDefaultDuration = () => _ExpressiveEffectsDefaultDuration;
export const ExpressiveEffectsSlow = () => _ExpressiveEffectsSlow;
export const ExpressiveEffectsSlowEasing = () => _ExpressiveEffectsSlowEasing;
export const ExpressiveEffectsSlowDuration = () => _ExpressiveEffectsSlowDuration;
export const Standard = () => _Standard;
export const StandardSpatial = () => _StandardSpatial;
export const StandardSpatialFast = () => _StandardSpatialFast;
export const StandardSpatialFastEasing = () => _StandardSpatialFastEasing;
export const StandardSpatialFastDuration = () => _StandardSpatialFastDuration;
export const StandardSpatialDefault = () => _StandardSpatialDefault;
export const StandardSpatialDefaultEasing = () => _StandardSpatialDefaultEasing;
export const StandardSpatialDefaultDuration = () => _StandardSpatialDefaultDuration;
export const StandardSpatialSlow = () => _StandardSpatialSlow;
export const StandardSpatialSlowEasing = () => _StandardSpatialSlowEasing;
export const StandardSpatialSlowDuration = () => _StandardSpatialSlowDuration;
export const StandardEffects = () => _StandardEffects;
export const StandardEffectsFast = () => _StandardEffectsFast;
export const StandardEffectsFastEasing = () => _StandardEffectsFastEasing;
export const StandardEffectsFastDuration = () => _StandardEffectsFastDuration;
export const StandardEffectsDefault = () => _StandardEffectsDefault;
export const StandardEffectsDefaultEasing = () => _StandardEffectsDefaultEasing;
export const StandardEffectsDefaultDuration = () => _StandardEffectsDefaultDuration;
export const StandardEffectsSlow = () => _StandardEffectsSlow;
export const StandardEffectsSlowEasing = () => _StandardEffectsSlowEasing;
export const StandardEffectsSlowDuration = () => _StandardEffectsSlowDuration;