import { CornerRadius, ShapeRadii } from "@internal/prelude";
import { Var } from "./Var.ts";

const _Full = null as unknown as Var<ShapeRadii>;
const _FullBl = null as unknown as Var<CornerRadius>;
const _FullBr = null as unknown as Var<CornerRadius>;
const _FullTl = null as unknown as Var<CornerRadius>;
const _FullTr = null as unknown as Var<CornerRadius>;
const _ExtraLargeTop = null as unknown as Var<ShapeRadii>;
const _ExtraLargeTopTl = null as unknown as Var<CornerRadius>;
const _ExtraLargeTopTr = null as unknown as Var<CornerRadius>;
const _ExtraLargeTopBl = null as unknown as Var<CornerRadius>;
const _ExtraLargeTopBr = null as unknown as Var<CornerRadius>;
const _ExtraLarge = null as unknown as Var<ShapeRadii>;
const _ExtraLargeTl = null as unknown as Var<CornerRadius>;
const _ExtraLargeTr = null as unknown as Var<CornerRadius>;
const _ExtraLargeBl = null as unknown as Var<CornerRadius>;
const _ExtraLargeBr = null as unknown as Var<CornerRadius>;
const _LargeTop = null as unknown as Var<ShapeRadii>;
const _LargeTopTl = null as unknown as Var<CornerRadius>;
const _LargeTopTr = null as unknown as Var<CornerRadius>;
const _LargeTopBl = null as unknown as Var<CornerRadius>;
const _LargeTopBr = null as unknown as Var<CornerRadius>;
const _LargeEnd = null as unknown as Var<ShapeRadii>;
const _LargeEndTr = null as unknown as Var<CornerRadius>;
const _LargeEndBr = null as unknown as Var<CornerRadius>;
const _LargeEndTl = null as unknown as Var<CornerRadius>;
const _LargeEndBl = null as unknown as Var<CornerRadius>;
const _LargeStart = null as unknown as Var<ShapeRadii>;
const _LargeStartTl = null as unknown as Var<CornerRadius>;
const _LargeStartBl = null as unknown as Var<CornerRadius>;
const _LargeStartTr = null as unknown as Var<CornerRadius>;
const _LargeStartBr = null as unknown as Var<CornerRadius>;
const _Large = null as unknown as Var<ShapeRadii>;
const _LargeTl = null as unknown as Var<CornerRadius>;
const _LargeTr = null as unknown as Var<CornerRadius>;
const _LargeBl = null as unknown as Var<CornerRadius>;
const _LargeBr = null as unknown as Var<CornerRadius>;
const _Medium = null as unknown as Var<ShapeRadii>;
const _MediumTl = null as unknown as Var<CornerRadius>;
const _MediumTr = null as unknown as Var<CornerRadius>;
const _MediumBl = null as unknown as Var<CornerRadius>;
const _MediumBr = null as unknown as Var<CornerRadius>;
const _Small = null as unknown as Var<ShapeRadii>;
const _SmallTl = null as unknown as Var<CornerRadius>;
const _SmallTr = null as unknown as Var<CornerRadius>;
const _SmallBl = null as unknown as Var<CornerRadius>;
const _SmallBr = null as unknown as Var<CornerRadius>;
const _ExtraSmallTop = null as unknown as Var<ShapeRadii>;
const _ExtraSmallTopTl = null as unknown as Var<CornerRadius>;
const _ExtraSmallTopTr = null as unknown as Var<CornerRadius>;
const _ExtraSmallTopBl = null as unknown as Var<CornerRadius>;
const _ExtraSmallTopBr = null as unknown as Var<CornerRadius>;
const _ExtraSmall = null as unknown as Var<ShapeRadii>;
const _ExtraSmallTl = null as unknown as Var<CornerRadius>;
const _ExtraSmallTr = null as unknown as Var<CornerRadius>;
const _ExtraSmallBl = null as unknown as Var<CornerRadius>;
const _ExtraSmallBr = null as unknown as Var<CornerRadius>;
const _None = null as unknown as Var<ShapeRadii>;
const _NoneTl = null as unknown as Var<CornerRadius>;
const _NoneTr = null as unknown as Var<CornerRadius>;
const _NoneBl = null as unknown as Var<CornerRadius>;
const _NoneBr = null as unknown as Var<CornerRadius>;
const _LargeIncreased = null as unknown as Var<ShapeRadii>;
const _LargeIncreasedTl = null as unknown as Var<CornerRadius>;
const _LargeIncreasedTr = null as unknown as Var<CornerRadius>;
const _LargeIncreasedBl = null as unknown as Var<CornerRadius>;
const _LargeIncreasedBr = null as unknown as Var<CornerRadius>;
const _ExtraLargeIncreased = null as unknown as Var<ShapeRadii>;
const _ExtraLargeIncreasedTl = null as unknown as Var<CornerRadius>;
const _ExtraLargeIncreasedTr = null as unknown as Var<CornerRadius>;
const _ExtraLargeIncreasedBl = null as unknown as Var<CornerRadius>;
const _ExtraLargeIncreasedBr = null as unknown as Var<CornerRadius>;
const _ExtraExtraLarge = null as unknown as Var<ShapeRadii>;
const _ExtraExtraLargeTl = null as unknown as Var<CornerRadius>;
const _ExtraExtraLargeTr = null as unknown as Var<CornerRadius>;
const _ExtraExtraLargeBl = null as unknown as Var<CornerRadius>;
const _ExtraExtraLargeBr = null as unknown as Var<CornerRadius>;

export const Full = () => _Full;
export const FullBl = () => _FullBl;
export const FullBr = () => _FullBr;
export const FullTl = () => _FullTl;
export const FullTr = () => _FullTr;
export const ExtraLargeTop = () => _ExtraLargeTop;
export const ExtraLargeTopTl = () => _ExtraLargeTopTl;
export const ExtraLargeTopTr = () => _ExtraLargeTopTr;
export const ExtraLargeTopBl = () => _ExtraLargeTopBl;
export const ExtraLargeTopBr = () => _ExtraLargeTopBr;
export const ExtraLarge = () => _ExtraLarge;
export const ExtraLargeTl = () => _ExtraLargeTl;
export const ExtraLargeTr = () => _ExtraLargeTr;
export const ExtraLargeBl = () => _ExtraLargeBl;
export const ExtraLargeBr = () => _ExtraLargeBr;
export const LargeTop = () => _LargeTop;
export const LargeTopTl = () => _LargeTopTl;
export const LargeTopTr = () => _LargeTopTr;
export const LargeTopBl = () => _LargeTopBl;
export const LargeTopBr = () => _LargeTopBr;
export const LargeEnd = () => _LargeEnd;
export const LargeEndTr = () => _LargeEndTr;
export const LargeEndBr = () => _LargeEndBr;
export const LargeEndTl = () => _LargeEndTl;
export const LargeEndBl = () => _LargeEndBl;
export const LargeStart = () => _LargeStart;
export const LargeStartTl = () => _LargeStartTl;
export const LargeStartBl = () => _LargeStartBl;
export const LargeStartTr = () => _LargeStartTr;
export const LargeStartBr = () => _LargeStartBr;
export const Large = () => _Large;
export const LargeTl = () => _LargeTl;
export const LargeTr = () => _LargeTr;
export const LargeBl = () => _LargeBl;
export const LargeBr = () => _LargeBr;
export const Medium = () => _Medium;
export const MediumTl = () => _MediumTl;
export const MediumTr = () => _MediumTr;
export const MediumBl = () => _MediumBl;
export const MediumBr = () => _MediumBr;
export const Small = () => _Small;
export const SmallTl = () => _SmallTl;
export const SmallTr = () => _SmallTr;
export const SmallBl = () => _SmallBl;
export const SmallBr = () => _SmallBr;
export const ExtraSmallTop = () => _ExtraSmallTop;
export const ExtraSmallTopTl = () => _ExtraSmallTopTl;
export const ExtraSmallTopTr = () => _ExtraSmallTopTr;
export const ExtraSmallTopBl = () => _ExtraSmallTopBl;
export const ExtraSmallTopBr = () => _ExtraSmallTopBr;
export const ExtraSmall = () => _ExtraSmall;
export const ExtraSmallTl = () => _ExtraSmallTl;
export const ExtraSmallTr = () => _ExtraSmallTr;
export const ExtraSmallBl = () => _ExtraSmallBl;
export const ExtraSmallBr = () => _ExtraSmallBr;
export const None = () => _None;
export const NoneTl = () => _NoneTl;
export const NoneTr = () => _NoneTr;
export const NoneBl = () => _NoneBl;
export const NoneBr = () => _NoneBr;
export const LargeIncreased = () => _LargeIncreased;
export const LargeIncreasedTl = () => _LargeIncreasedTl;
export const LargeIncreasedTr = () => _LargeIncreasedTr;
export const LargeIncreasedBl = () => _LargeIncreasedBl;
export const LargeIncreasedBr = () => _LargeIncreasedBr;
export const ExtraLargeIncreased = () => _ExtraLargeIncreased;
export const ExtraLargeIncreasedTl = () => _ExtraLargeIncreasedTl;
export const ExtraLargeIncreasedTr = () => _ExtraLargeIncreasedTr;
export const ExtraLargeIncreasedBl = () => _ExtraLargeIncreasedBl;
export const ExtraLargeIncreasedBr = () => _ExtraLargeIncreasedBr;
export const ExtraExtraLarge = () => _ExtraExtraLarge;
export const ExtraExtraLargeTl = () => _ExtraExtraLargeTl;
export const ExtraExtraLargeTr = () => _ExtraExtraLargeTr;
export const ExtraExtraLargeBl = () => _ExtraExtraLargeBl;
export const ExtraExtraLargeBr = () => _ExtraExtraLargeBr;
