import { Float, Spring } from "@internal/prelude";
import { Var } from "./Var.ts";

const _SpatialFast = null as unknown as Var<Spring>;
const _SpatialFastDamping = null as unknown as Var<Float>;
const _SpatialFastStiffness = null as unknown as Var<Float>;
const _SpatialDefault = null as unknown as Var<Spring>;
const _SpatialDefaultDamping = null as unknown as Var<Float>;
const _SpatialDefaultStiffness = null as unknown as Var<Float>;
const _SpatialSlow = null as unknown as Var<Spring>;
const _SpatialSlowDamping = null as unknown as Var<Float>;
const _SpatialSlowStiffness = null as unknown as Var<Float>;
const _EffectsFast = null as unknown as Var<Spring>;
const _EffectsFastDamping = null as unknown as Var<Float>;
const _EffectsFastStiffness = null as unknown as Var<Float>;
const _EffectsDefault = null as unknown as Var<Spring>;
const _EffectsDefaultDamping = null as unknown as Var<Float>;
const _EffectsDefaultStiffness = null as unknown as Var<Float>;
const _EffectsSlow = null as unknown as Var<Spring>;
const _EffectsSlowDamping = null as unknown as Var<Float>;
const _EffectsSlowStiffness = null as unknown as Var<Float>;

export const SpatialFast = () => _SpatialFast;
export const SpatialFastDamping = () => _SpatialFastDamping;
export const SpatialFastStiffness = () => _SpatialFastStiffness;
export const SpatialDefault = () => _SpatialDefault;
export const SpatialDefaultDamping = () => _SpatialDefaultDamping;
export const SpatialDefaultStiffness = () => _SpatialDefaultStiffness;
export const SpatialSlow = () => _SpatialSlow;
export const SpatialSlowDamping = () => _SpatialSlowDamping;
export const SpatialSlowStiffness = () => _SpatialSlowStiffness;
export const EffectsFast = () => _EffectsFast;
export const EffectsFastDamping = () => _EffectsFastDamping;
export const EffectsFastStiffness = () => _EffectsFastStiffness;
export const EffectsDefault = () => _EffectsDefault;
export const EffectsDefaultDamping = () => _EffectsDefaultDamping;
export const EffectsDefaultStiffness = () => _EffectsDefaultStiffness;
export const EffectsSlow = () => _EffectsSlow;
export const EffectsSlowDamping = () => _EffectsSlowDamping;
export const EffectsSlowStiffness = () => _EffectsSlowStiffness;
