import { Vars, MaybeVar, Color, Dp, ShapeRadii, ShapesRef, TextStyle, TypescaleRef, Ui } from "@internal/prelude";

export interface Assist {
  readonly container_shape: MaybeVar<ShapeRadii>,
  readonly container_height: Dp,
  readonly container_elevation: MaybeVar<Elevation>,
  readonly elevated_container_color: MaybeVar<Color>,
  readonly elevated_container_shadow_color: MaybeVar<Color>,
  readonly elevated_container_elevation: MaybeVar<Elevation>,
  readonly elevated_disabled_container_color: MaybeVar<Color>,
  readonly elevated_disabled_container_opacity: MaybeVar<Opacity>,
  readonly elevated_disabled_container_elevation: MaybeVar<Elevation>,
  readonly elevated_hover_container_elevation: MaybeVar<Elevation>,

  readonly container_outline_color: MaybeVar<Color>,
  readonly container_outline_width: Dp,
  readonly disabled_outline_color: MaybeVar<Color>,
  readonly disabled_outline_opacity: MaybeVar<Opacity>,
  readonly focus_outline_color: MaybeVar<Color>,

  readonly label_text_type_role: MaybeVar<TextStyle>,
  readonly label_text_color: MaybeVar<Color>,
  readonly disabled_label_text_color: MaybeVar<Color>,
  readonly disabled_label_text_opacity: MaybeVar<Opacity>,
  readonly hover_label_text_color: MaybeVar<Color>,

  readonly icon_size: Dp,
  readonly icon_color: MaybeVar<Color>,
  readonly with_icon_disabled_icon_color: MaybeVar<Color>,
  readonly with_icon_disabled_icon_opacity: MaybeVar<Opacity>,
  readonly with_icon_hover_icon_color: MaybeVar<Color>,

  readonly hover_state_layer_color: MaybeVar<Color>,
  readonly hover_state_layer_opacity: MaybeVar<Opacity>,

  readonly focus_indicator_color: MaybeVar<Color>,
  readonly focus_indicator_thickness: Dp,
  readonly focus_indicator_offset: Dp,
  
  readonly elevated_focus_container_elevation: MaybeVar<Elevation>,
  readonly focus_label_text_color: MaybeVar<Color>,
  readonly focus_state_layer_color: MaybeVar<Color>,
  readonly focus_state_layer_opacity: MaybeVar<Opacity>,
  readonly with_icon_focus_icon_color: MaybeVar<Color>,

  readonly elevated_pressed_container_elevation: MaybeVar<Elevation>,
  readonly pressed_label_text_color: MaybeVar<Color>,
  readonly pressed_state_layer_color: MaybeVar<Color>,
  readonly pressed_state_layer_opacity: MaybeVar<Opacity>,
  readonly with_icon_pressed_icon_color: MaybeVar<Color>,

  readonly dragged_container_elevation: MaybeVar<Elevation>,
  readonly dragged_label_text_color: MaybeVar<Color>,
  readonly dragged_state_layer_color: MaybeVar<Color>,
  readonly dragged_state_layer_opacity: MaybeVar<Opacity>,
  readonly with_icon_dragged_icon_color: MaybeVar<Color>,
}

export interface Filter {
  readonly container_shape: MaybeVar<ShapeRadii>,
  readonly container_height: Dp,
  readonly container_shadow_color: MaybeVar<Color>,
  readonly container_elevation: MaybeVar<Elevation>,
  readonly unselected_outline_color: MaybeVar<Color>,
  readonly unselected_outline_width: Dp,
  readonly selected_outline_color: MaybeVar<Color>,
  readonly selected_outline_width: Dp,
  readonly elevated_container_elevation: MaybeVar<Elevation>,
  readonly elevated_container_shadow_color: MaybeVar<Color>,
  readonly elevated_unselected_container_color: MaybeVar<Color>,
  readonly elevated_selected_container_color: MaybeVar<Color>,

  readonly label_text_type_role: MaybeVar<TextStyle>,
  readonly unselected_label_text_color: MaybeVar<Color>,
  readonly selected_label_text_color: MaybeVar<Color>,
  readonly with_icon_icon_size: Dp,
  readonly with_leading_icon_selected_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_leading_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_trailing_icon_color: MaybeVar<Color>,

  readonly disabled_unselected_outline_color: MaybeVar<Color>,
  readonly disabled_unselected_outline_opacity: MaybeVar<Opacity>,
  readonly disabled_selected_container_color: MaybeVar<Color>,
  readonly disabled_selected_container_opacity: MaybeVar<Opacity>,
  readonly elevated_disabled_container_elevation: MaybeVar<Elevation>,
  readonly elevated_disabled_container_color: MaybeVar<Color>,
  readonly elevated_disabled_container_opacity: MaybeVar<Opacity>,
  readonly disabled_label_text_color: MaybeVar<Color>,
  readonly disabled_label_text_opacity: MaybeVar<Opacity>,
  readonly with_leading_icon_disabled_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_disabled_leading_icon_opacity: MaybeVar<Opacity>,
  readonly with_trailing_icon_disabled_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_disabled_trailing_icon_opacity: MaybeVar<Opacity>,

  readonly focus_indicator_color: MaybeVar<Color>,
  readonly focus_indicator_thickness: Dp,
  readonly focus_indicator_offset: Dp,
  readonly unselected_focus_outline_color: MaybeVar<Color>,
  readonly elevated_focus_container_elevation: MaybeVar<Elevation>,
  readonly selected_focus_container_elevation: MaybeVar<Elevation>,
  readonly unselected_focus_container_elevation: MaybeVar<Elevation>,
  readonly unselected_focus_label_text_color: MaybeVar<Color>,
  readonly selected_focus_label_text_color: MaybeVar<Color>,
  readonly unselected_focus_state_layer_color: MaybeVar<Color>,
  readonly unselected_focus_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_focus_state_layer_color: MaybeVar<Color>,
  readonly selected_focus_state_layer_opacity: MaybeVar<Opacity>,
  readonly with_leading_icon_selected_focus_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_focus_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_focus_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_focus_icon_color: MaybeVar<Color>,

  readonly elevated_hover_container_elevation: MaybeVar<Elevation>,
  readonly selected_hover_container_elevation: MaybeVar<Elevation>,
  readonly unselected_hover_container_elevation: MaybeVar<Elevation>,
  readonly unselected_hover_label_text_color: MaybeVar<Color>,
  readonly selected_hover_label_text_color: MaybeVar<Color>,
  readonly unselected_hover_state_layer_color: MaybeVar<Color>,
  readonly unselected_hover_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_hover_state_layer_color: MaybeVar<Color>,
  readonly selected_hover_state_layer_opacity: MaybeVar<Opacity>,
  readonly with_leading_icon_selected_hover_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_hover_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_hover_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_hover_icon_color: MaybeVar<Color>,

  readonly elevated_style_pressed_container_elevation: MaybeVar<Elevation>,
  readonly selected_pressed_container_elevation: MaybeVar<Elevation>,
  readonly unselected_pressed_container_elevation: MaybeVar<Elevation>,
  readonly unselected_pressed_label_text_color: MaybeVar<Color>,
  readonly selected_pressed_label_text_color: MaybeVar<Color>,
  readonly unselected_pressed_state_layer_color: MaybeVar<Color>,
  readonly unselected_pressed_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_pressed_state_layer_color: MaybeVar<Color>,
  readonly selected_pressed_state_layer_opacity: MaybeVar<Opacity>,
  readonly with_leading_icon_selected_pressed_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_pressed_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_pressed_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_pressed_icon_color: MaybeVar<Color>,

  readonly dragged_container_elevation: MaybeVar<Elevation>,
  readonly unselected_dragged_label_text_color: MaybeVar<Color>,
  readonly selected_dragged_label_text_color: MaybeVar<Color>,
  readonly unselected_dragged_state_layer_color: MaybeVar<Color>,
  readonly unselected_dragged_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_dragged_state_layer_color: MaybeVar<Color>,
  readonly selected_dragged_state_layer_opacity: MaybeVar<Opacity>,
  readonly with_leading_icon_selected_dragged_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_dragged_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_dragged_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_dragged_icon_color: MaybeVar<Color>,
}

export interface Input {
  readonly selected_container_color: MaybeVar<Color>,
  readonly container_shape: MaybeVar<ShapeRadii>,
  readonly container_height: Dp,
  readonly container_elevation: MaybeVar<Elevation>,
  readonly disabled_selected_container_color: MaybeVar<Color>,
  readonly disabled_selected_container_opacity: MaybeVar<Opacity>,
  readonly dragged_container_elevation: MaybeVar<Elevation>,

  readonly unselected_outline_color: MaybeVar<Color>,
  readonly unselected_outline_width: Dp,
  readonly selected_outline_width: Dp,
  readonly disabled_unselected_outline_color: MaybeVar<Color>,
  readonly disabled_unselected_outline_opacity: MaybeVar<Opacity>,
  readonly unselected_focused_outline_color: MaybeVar<Color>,

  readonly label_text_type_role: MaybeVar<TextStyle>,
  readonly selected_label_text_color: MaybeVar<Color>,
  readonly unselected_label_text_color: MaybeVar<Color>,
  readonly disabled_label_text_color: MaybeVar<Color>,
  readonly disabled_label_text_opacity: MaybeVar<Opacity>,
  readonly unselected_hover_label_text_color: MaybeVar<Color>,
  readonly selected_hover_label_text_color: MaybeVar<Color>,
  readonly unselected_focus_label_text_color: MaybeVar<Color>,
  readonly selected_focus_label_text_color: MaybeVar<Color>,
  readonly unselected_pressed_label_text_color: MaybeVar<Color>,
  readonly selected_pressed_label_text_color: MaybeVar<Color>,
  readonly unselected_dragged_label_text_color: MaybeVar<Color>,
  readonly selected_dragged_label_text_color: MaybeVar<Color>,

  readonly with_avatar_avatar_size: Dp,
  readonly with_avatar_avatar_shape: MaybeVar<ShapeRadii>,
  readonly with_avatar_disabled_avatar_opacity: MaybeVar<Opacity>,

  readonly leading_icon_size: Dp,
  readonly with_leading_icon_selected_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_disabled_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_disabled_leading_icon_opacity: MaybeVar<Opacity>,
  readonly with_leading_icon_unselected_hover_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_selected_hover_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_focus_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_selected_focus_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_pressed_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_selected_pressed_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_unselected_dragged_leading_icon_color: MaybeVar<Color>,
  readonly with_leading_icon_selected_dragged_leading_icon_color: MaybeVar<Color>,

  readonly trailing_icon_size: Dp,
  readonly with_trailing_icon_selected_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_disabled_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_disabled_trailing_icon_opacity: MaybeVar<Opacity>,
  readonly with_trailing_icon_unselected_hover_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_hover_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_focus_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_focus_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_pressed_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_pressed_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_unselected_dragged_trailing_icon_color: MaybeVar<Color>,
  readonly with_trailing_icon_selected_dragged_trailing_icon_color: MaybeVar<Color>,

  readonly unselected_hover_state_layer_color: MaybeVar<Color>,
  readonly unselected_hover_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_hover_state_layer_color: MaybeVar<Color>,
  readonly selected_hover_state_layer_opacity: MaybeVar<Opacity>,

  readonly focus_indicator_color: MaybeVar<Color>,
  readonly focus_indicator_thickness: Dp,
  readonly focus_indicator_offset: Dp,

  readonly unselected_focus_state_layer_color: MaybeVar<Color>,
  readonly unselected_focus_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_focus_state_layer_color: MaybeVar<Color>,
  readonly selected_focus_state_layer_opacity: MaybeVar<Opacity>,

  readonly unselected_pressed_state_layer_color: MaybeVar<Color>,
  readonly unselected_pressed_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_pressed_state_layer_color: MaybeVar<Color>,
  readonly selected_pressed_state_layer_opacity: MaybeVar<Opacity>,

  readonly unselected_dragged_state_layer_color: MaybeVar<Color>,
  readonly unselected_dragged_state_layer_opacity: MaybeVar<Opacity>,
  readonly selected_dragged_state_layer_color: MaybeVar<Color>,
  readonly selected_dragged_state_layer_opacity: MaybeVar<Opacity>,
}

export interface Suggestion {
  readonly container_shape: MaybeVar<ShapeRadii>,
  readonly container_height: Dp,
  readonly container_elevation: MaybeVar<Elevation>,
  readonly container_outline_color: MaybeVar<Color>,
  readonly container_outline_width: Dp,
  readonly elevated_container_elevation: MaybeVar<Elevation>,
  readonly elevated_container_color: MaybeVar<Color>,
  readonly elevated_container_shadow_color: MaybeVar<Color>,
  readonly leading_icon_color: MaybeVar<Color>,
  readonly leading_icon_size: Dp,

  readonly label_text_type_role: MaybeVar<TextStyle>,
  readonly label_text_color: MaybeVar<Color>,

  readonly disabled_outline_color: MaybeVar<Color>,
  readonly disabled_outline_opacity: MaybeVar<Opacity>,
  readonly elevated_disabled_container_elevation: MaybeVar<Elevation>,
  readonly elevated_disabled_container_color: MaybeVar<Color>,
  readonly elevated_disabled_container_opacity: MaybeVar<Opacity>,
  readonly disabled_leading_icon_color: MaybeVar<Color>,
  readonly disabled_leading_icon_opacity: MaybeVar<Opacity>,
  readonly disabled_label_text_color: MaybeVar<Color>,
  readonly disabled_label_text_opacity: MaybeVar<Opacity>,

  readonly elevated_hover_container_elevation: MaybeVar<Elevation>,
  readonly hover_leading_icon_color: MaybeVar<Color>,
  readonly hover_label_text_color: MaybeVar<Color>,
  readonly elevated_hover_state_layer_color: MaybeVar<Color>,
  readonly elevated_hover_state_layer_opacity: MaybeVar<Opacity>,

  readonly focus_indicator_color: MaybeVar<Color>,
  readonly focus_indicator_thickness: Dp,
  readonly focus_indicator_offset: Dp,

  readonly focus_outline_color: MaybeVar<Color>,
  readonly elevated_focus_container_elevation: MaybeVar<Elevation>,
  readonly focus_leading_icon_color: MaybeVar<Color>,
  readonly focus_label_text_color: MaybeVar<Color>,
  readonly focus_state_layer_color: MaybeVar<Color>,
  readonly focus_state_layer_opacity: MaybeVar<Opacity>,

  readonly elevated_pressed_container_elevation: MaybeVar<Elevation>,
  readonly pressed_leading_icon_color: MaybeVar<Color>,
  readonly elevated_pressed_label_text_color: MaybeVar<Color>,
  readonly elevated_pressed_state_layer_color: MaybeVar<Color>,
  readonly elevated_pressed_state_layer_opacity: MaybeVar<Opacity>,

  readonly dragged_container_elevation: MaybeVar<Elevation>,
  readonly dragged_leading_icon_color: MaybeVar<Color>,
  readonly dragged_label_text_color: MaybeVar<Color>,
  readonly dragged_state_layer_color: MaybeVar<Color>,
  readonly dragged_state_layer_opacity: MaybeVar<Opacity>,
}
