import { 
  FontSize, FontTracking, LineHeight, Pt, 
  TypefaceRef, TextStyle,
} from "@internal/prelude";

export interface Typescale {
  readonly displayLarge: TextStyle,
  readonly displayMedium: TextStyle,
  readonly displaySmall: TextStyle,
  readonly headlineLarge: TextStyle,
  readonly headlineMedium: TextStyle,
  readonly headlineSmall: TextStyle,
  readonly titleLarge: TextStyle,
  readonly titleMedium: TextStyle,
  readonly titleSmall: TextStyle,
  readonly bodyLarge: TextStyle,
  readonly bodyMedium: TextStyle,
  readonly bodySmall: TextStyle,
  readonly labelLarge: TextStyle,
  readonly labelMedium: TextStyle,
  readonly labelSmall: TextStyle,
  readonly emphasizedDisplayLarge: TextStyle,
  readonly emphasizedDisplayMedium: TextStyle,
  readonly emphasizedDisplaySmall: TextStyle,
  readonly emphasizedHeadlineLarge: TextStyle,
  readonly emphasizedHeadlineMedium: TextStyle,
  readonly emphasizedHeadlineSmall: TextStyle,
  readonly emphasizedTitleLarge: TextStyle,
  readonly emphasizedTitleMedium: TextStyle,
  readonly emphasizedTitleSmall: TextStyle,
  readonly emphasizedBodyLarge: TextStyle,
  readonly emphasizedBodyMedium: TextStyle,
  readonly emphasizedBodySmall: TextStyle,
  readonly emphasizedLabelLarge: TextStyle,
  readonly emphasizedLabelMedium: TextStyle,
  readonly emphasizedLabelSmall: TextStyle,
}

export const baseline = () => ({
  displayLarge: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(57)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(64)),
  },
  displayMedium: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(45)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(52)),
  },
  displaySmall: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(36)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(44)),
  },
  headlineLarge: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(32)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(40)),
  },
  headlineMedium: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(28)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(36)),
  },
  headlineSmall: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(24)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(32)),
  },
  titleLarge: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(22)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(28)),
  },
  titleMedium: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(16)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(24)),
  },
  titleSmall: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(14)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(20)),
  },
  bodyLarge: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(16)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(24)),
  },
  bodyMedium: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(14)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(20)),
  },
  bodySmall: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightRegular(),
    size: FontSize.create(Pt.create(12)),
    tracking: FontTracking.create(Pt.create(0.1)),
    lineHeight: LineHeight.create(Pt.create(16)),
  },
  labelLarge: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(14)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(20)),
    // prominent_weight: TypefaceRef.WeightBold(),
  },
  labelMedium: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(12)),
    tracking: FontTracking.create(Pt.create(0.1)),
    lineHeight: LineHeight.create(Pt.create(16)),
    // prominent_weight: TypefaceRef.WeightBold(),
  },
  labelSmall: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(11)),
    tracking: FontTracking.create(Pt.create(0.1)),
    lineHeight: LineHeight.create(Pt.create(16)),
  },
  emphasizedDisplayLarge: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(57)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(64)),
  },
  emphasizedDisplayMedium: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(45)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(52)),
  },
  emphasizedDisplaySmall: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(36)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(44)),
  },
  emphasizedHeadlineLarge: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(32)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(40)),
  },
  emphasizedHeadlineMedium: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(28)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(36)),
  },
  emphasizedHeadlineSmall: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(24)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(32)),
  },
  emphasizedTitleLarge: {
    family: TypefaceRef.Brand(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(22)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(28)),
  },
  emphasizedTitleMedium: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightBold(),
    size: FontSize.create(Pt.create(16)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(24)),
  },
  emphasizedTitleSmall: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightBold(),
    size: FontSize.create(Pt.create(14)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(20)),
  },
  emphasizedBodyLarge: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(16)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(24)),
  },
  emphasizedBodyMedium: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(14)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(20)),
  },
  emphasizedBodySmall: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightMedium(),
    size: FontSize.create(Pt.create(12)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(16)),
  },
  emphasizedLabelLarge: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightBold(),
    size: FontSize.create(Pt.create(14)),
    tracking: FontTracking.create(Pt.create(0)),
    lineHeight: LineHeight.create(Pt.create(20)),
  },
  emphasizedLabelMedium: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightBold(),
    size: FontSize.create(Pt.create(12)),
    tracking: FontTracking.create(Pt.create(0.1)),
    lineHeight: LineHeight.create(Pt.create(16)),
  },
  emphasizedLabelSmall: {
    family: TypefaceRef.Plain(),
    weight: TypefaceRef.WeightBold(),
    size: FontSize.create(Pt.create(11)),
    tracking: FontTracking.create(Pt.create(0.1)),
    lineHeight: LineHeight.create(Pt.create(16)),
  },
});