import { Vars, MaybeVar, Dp, HexColor, Color, Ui } from "@internal/prelude";

export interface Filled {
  readonly containerColor: MaybeVar<Color>,
  readonly shadowColor: MaybeVar<Color>,
  readonly elevation: MaybeVar<Elevation>,
  readonly labelColor: MaybeVar<Color>,
  readonly iconColor: MaybeVar<Color>,
  readonly disabledContainerColor: MaybeVar<Color>,
  readonly disabledContainerOpacity: MaybeVar<Opacity>,
  readonly disabledContainerElevation: MaybeVar<Elevation>,
  readonly disabledLabelColor: MaybeVar<Color>,
  readonly disabledLabelOpacity: MaybeVar<Opacity>,
  readonly disabledIconColor: MaybeVar<Color>,
  readonly disabledIconOpacity: MaybeVar<Opacity>,
  readonly hoveredContainerStateLayerColor: MaybeVar<Color>,
  readonly hoveredContainerStateLayerOpacity: MaybeVar<Opacity>,
  readonly hoveredLabelColor: MaybeVar<Color>,
  readonly hoveredIconColor: MaybeVar<Color>,
  readonly focusedContainerStateLayerColor: MaybeVar<Color>,
  readonly focusedContainerStateLayerOpacity: MaybeVar<Opacity>,
  readonly focusedContainerStateLayerElevation: MaybeVar<Elevation>,
  readonly focusedLabelColor: MaybeVar<Color>,
  readonly focusedIconColor: MaybeVar<Color>,
  readonly pressedContainerStateLayerColor: MaybeVar<Color>,
  readonly pressedContainerStateLayerOpacity: MaybeVar<Opacity>,
  readonly pressedContainerStateLayerElevation: MaybeVar<Elevation>,
  readonly pressedLabelColor: MaybeVar<Color>,
  readonly pressedIconColor: MaybeVar<Color>,

  readonly toggleUnselectedContainerColor: MaybeVar<Color>,
  readonly toggleUnselectedLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedIconColor: MaybeVar<Color>,
  readonly toggleUnselectedHoveredContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleUnselectedHoveredLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedHoveredIconColor: MaybeVar<Color>,
  readonly toggleUnselectedFocusedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleUnselectedFocusedLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedFocusedIconColor: MaybeVar<Color>,
  readonly toggleUnselectedPressedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleUnselectedPressedLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedPressedIconColor: MaybeVar<Color>,

  readonly toggleSelectedContainerColor: MaybeVar<Color>,
  readonly toggleSelectedLabelColor: MaybeVar<Color>,
  readonly toggleSelectedIconColor: MaybeVar<Color>,
  readonly toggleSelectedHoveredContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleSelectedHoveredLabelColor: MaybeVar<Color>,
  readonly toggleSelectedHoveredIconColor: MaybeVar<Color>,
  readonly toggleSelectedFocusedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleSelectedFocusedLabelColor: MaybeVar<Color>,
  readonly toggleSelectedFocusedIconColor: MaybeVar<Color>,
  readonly toggleSelectedPressedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleSelectedPressedLabelColor: MaybeVar<Color>,
  readonly toggleSelectedPressedIconColor: MaybeVar<Color>,
}

export const baseline = (): Filled => {
  return {
    containerColor: Vars.ColorScheme.Primary(),
    shadowColor: Vars.ColorScheme.Shadow(),
    elevation: Vars.ElevationScheme.Level0(),
    labelColor: Vars.ColorScheme.OnPrimary(),
    iconColor: Vars.ColorScheme.OnPrimary(),
    disabledContainerColor: Vars.ColorScheme.OnSurface(),
    disabledContainerOpacity: Ui.create(0.1),
    disabledContainerElevation: Vars.ElevationScheme.Level0(),
    disabledLabelColor: Vars.ColorScheme.OnSurface(),
    disabledLabelOpacity: Ui.create(0.38),
    disabledIconColor: Vars.ColorScheme.OnSurface(),
    disabledIconOpacity: Ui.create(0.38),
    hoveredContainerStateLayerColor: Vars.ColorScheme.OnPrimary(),
    hoveredContainerStateLayerOpacity: Vars.Opacities.Hovered(),
    hoveredLabelColor: Vars.ColorScheme.OnPrimary(),
    hoveredIconColor: Vars.ColorScheme.OnPrimary(),
    focusedContainerStateLayerColor: Vars.ColorScheme.OnPrimary(),
    focusedContainerStateLayerOpacity: Vars.Opacities.Focused(),
    focusedContainerStateLayerElevation: Vars.ElevationScheme.Level0(),
    focusedLabelColor: Vars.ColorScheme.OnPrimary(),
    focusedIconColor: Vars.ColorScheme.OnPrimary(),
    pressedContainerStateLayerColor: Vars.ColorScheme.OnPrimary(),
    pressedContainerStateLayerOpacity: Vars.Opacities.Pressed(),
    pressedContainerStateLayerElevation: Vars.ElevationScheme.Level0(),
    pressedLabelColor: Vars.ColorScheme.OnPrimary(),
    pressedIconColor: Vars.ColorScheme.OnPrimary(),

    toggleUnselectedContainerColor: Vars.ColorScheme.SurfaceContainer(),
    toggleUnselectedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedHoveredContainerStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedHoveredLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedHoveredIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedFocusedContainerStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedFocusedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedFocusedIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedPressedContainerStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedPressedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedPressedIconColor: Vars.ColorScheme.OnSurfaceVariant(),

    toggleSelectedContainerColor: Vars.ColorScheme.Primary(),
    toggleSelectedLabelColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedIconColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedHoveredContainerStateLayerColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedHoveredLabelColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedHoveredIconColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedFocusedContainerStateLayerColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedFocusedLabelColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedFocusedIconColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedPressedContainerStateLayerColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedPressedLabelColor: Vars.ColorScheme.OnPrimary(),
    toggleSelectedPressedIconColor: Vars.ColorScheme.OnPrimary(),
  };
};
