import { Vars, MaybeVar, HexColor, Color, Ui } from "@internal/prelude";

export interface Outlined {
  readonly outlineColor: MaybeVar<Color>,
  readonly labelColor: MaybeVar<Color>,
  readonly iconColor: MaybeVar<Color>,
  readonly disabledOutlineColor: MaybeVar<Color>,
  readonly disabledContainerOpacity: MaybeVar<Opacity>,
  readonly disabledLabelColor: MaybeVar<Color>,
  readonly disabledLabelOpacity: MaybeVar<Opacity>,
  readonly disabledIconColor: MaybeVar<Color>,
  readonly disabledIconOpacity: MaybeVar<Opacity>,
  readonly hoveredStateLayerColor: MaybeVar<Color>,
  readonly hoveredStateLayerOpacity: MaybeVar<Opacity>,
  readonly hoveredOutlineColor: MaybeVar<Color>,
  readonly hoveredLabelColor: MaybeVar<Color>,
  readonly hoveredIconColor: MaybeVar<Color>,
  readonly focusedContainerStateLayerColor: MaybeVar<Color>,
  readonly focusedContainerStateLayerOpacity: MaybeVar<Opacity>,
  readonly focusedOutlineColor: MaybeVar<Color>,
  readonly focusedLabelColor: MaybeVar<Color>,
  readonly focusedIconColor: MaybeVar<Color>,
  readonly pressedContainerStateLayerColor: MaybeVar<Color>,
  readonly pressedContainerStateLayerOpacity: MaybeVar<Opacity>,
  readonly pressedOutlineColor: MaybeVar<Color>,
  readonly pressedLabelColor: MaybeVar<Color>,
  readonly pressedIconColor: MaybeVar<Color>,

  readonly toggleUnselectedLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedIconColor: MaybeVar<Color>,
  readonly toggleUnselectedDisabledOutlineColor: MaybeVar<Color>,
  readonly toggleUnselectedHoveredStateLayerColor: MaybeVar<Color>,
  readonly toggleUnselectedHoveredOutlineColor: MaybeVar<Color>,
  readonly toggleUnselectedHoveredLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedHoveredIconColor: MaybeVar<Color>,
  readonly toggleUnselectedFocusedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleUnselectedFocusedOutlineColor: MaybeVar<Color>,
  readonly toggleUnselectedFocusedLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedFocusedIconColor: MaybeVar<Color>,
  readonly toggleUnselectedPressedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleUnselectedPressedOutlineColor: MaybeVar<Color>,
  readonly toggleUnselectedPressedLabelColor: MaybeVar<Color>,
  readonly toggleUnselectedPressedIconColor: MaybeVar<Color>,

  readonly toggleSelectedContainerColor: MaybeVar<Color>,
  readonly toggleSelectedLabelColor: MaybeVar<Color>,
  readonly toggleSelectedIconColor: MaybeVar<Color>,
  readonly toggleSelectedDisabledContainerColor: MaybeVar<Color>,
  readonly toggleSelectedHoveredStateLayerColor: MaybeVar<Color>,
  readonly toggleSelectedHoveredLabelColor: MaybeVar<Color>,
  readonly toggleSelectedHoveredIconColor: MaybeVar<Color>,
  readonly toggleSelectedFocusedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleSelectedFocusedLabelColor: MaybeVar<Color>,
  readonly toggleSelectedFocusedIconColor: MaybeVar<Color>,
  readonly toggleSelectedPressedContainerStateLayerColor: MaybeVar<Color>,
  readonly toggleSelectedPressedLabelColor: MaybeVar<Color>,
  readonly toggleSelectedPressedIconColor: MaybeVar<Color>,
}

export const baseline = (): Outlined => {
  return {
    outlineColor: Vars.ColorScheme.OutlineVariant(),
    labelColor: Vars.ColorScheme.OnSurfaceVariant(),
    iconColor: Vars.ColorScheme.OnSurfaceVariant(),
    disabledOutlineColor: Vars.ColorScheme.OutlineVariant(),
    disabledContainerOpacity: Ui.create(0.1),
    disabledLabelColor: Vars.ColorScheme.OnSurface(),
    disabledLabelOpacity: Ui.create(0.38),
    disabledIconColor: Vars.ColorScheme.OnSurface(),
    disabledIconOpacity: Ui.create(0.38),
    hoveredStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    hoveredStateLayerOpacity: Vars.Opacities.Hovered(),
    hoveredOutlineColor: Vars.ColorScheme.OutlineVariant(),
    hoveredLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    hoveredIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    focusedContainerStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    focusedContainerStateLayerOpacity: Vars.Opacities.Focused(),
    focusedOutlineColor: Vars.ColorScheme.OutlineVariant(),
    focusedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    focusedIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    pressedContainerStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    pressedContainerStateLayerOpacity: Vars.Opacities.Pressed(),
    pressedOutlineColor: Vars.ColorScheme.OutlineVariant(),
    pressedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    pressedIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    
    toggleUnselectedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedDisabledOutlineColor: Vars.ColorScheme.OutlineVariant(),
    toggleUnselectedHoveredStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedHoveredOutlineColor: Vars.ColorScheme.OutlineVariant(),
    toggleUnselectedHoveredLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedHoveredIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedFocusedContainerStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedFocusedOutlineColor: Vars.ColorScheme.OutlineVariant(),
    toggleUnselectedFocusedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedFocusedIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedPressedContainerStateLayerColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedPressedOutlineColor: Vars.ColorScheme.OutlineVariant(),
    toggleUnselectedPressedLabelColor: Vars.ColorScheme.OnSurfaceVariant(),
    toggleUnselectedPressedIconColor: Vars.ColorScheme.OnSurfaceVariant(),

    toggleSelectedContainerColor: Vars.ColorScheme.InverseSurface(),
    toggleSelectedLabelColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedIconColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedDisabledContainerColor: Vars.ColorScheme.OnSurface(),
    toggleSelectedHoveredStateLayerColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedHoveredLabelColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedHoveredIconColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedFocusedContainerStateLayerColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedFocusedLabelColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedFocusedIconColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedPressedContainerStateLayerColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedPressedLabelColor: Vars.ColorScheme.InverseOnSurface(),
    toggleSelectedPressedIconColor: Vars.ColorScheme.InverseOnSurface(),
  };
};