import { Length, MaybeVar, TextStyle, Dp, ShapeRadii, Spring, Curve, Vars } from "@internal/prelude";

export interface Size {
  readonly containerHeight: Length,
  readonly outlineWidth: Length,
  readonly labelStyle: MaybeVar<TextStyle>,
  readonly iconSize: Dp,
  readonly shapeRound: MaybeVar<ShapeRadii>,
  readonly shapeSquare: MaybeVar<ShapeRadii>,
  readonly leadingSpace: Dp,
  readonly middleSpace: Dp,
  readonly trailingSpace: Dp,
  readonly shapePessedMorph: MaybeVar<ShapeRadii>,
  readonly shapeMorphAnimationSpring: MaybeVar<Spring>,
  readonly shapeMorphAnimationCurve: MaybeVar<Curve>,
  readonly selectedContainerShapeRound: MaybeVar<ShapeRadii>,
  readonly selectedContainerShapeSquare: MaybeVar<ShapeRadii>,
}

export const ExtraSmall = (): Size => ({
  containerHeight: Dp.create(32),
  outlineWidth: Dp.create(1),
  labelStyle: Vars.Typescale.LabelLarge(),
  iconSize: Dp.create(20),
  shapeRound: Vars.ShapeScheme.Full(),
  shapeSquare: Vars.ShapeScheme.Medium(),
  leadingSpace: Dp.create(12),
  middleSpace: Dp.create(8),
  trailingSpace: Dp.create(12),
  shapePessedMorph: Vars.ShapeScheme.Small(),
  shapeMorphAnimationSpring: Vars.SpringScheme.SpatialFast(),
  shapeMorphAnimationCurve: Vars.CurveScheme.ExpressiveSpatialFast(),
  selectedContainerShapeRound: Vars.ShapeScheme.Medium(),
  selectedContainerShapeSquare: Vars.ShapeScheme.Full(),
});

export const Small = (): Size => ({
  containerHeight: Dp.create(40),
  outlineWidth: Dp.create(1),
  labelStyle: Vars.Typescale.LabelLarge(),
  iconSize: Dp.create(20),
  shapeRound: Vars.ShapeScheme.Full(),
  shapeSquare: Vars.ShapeScheme.Medium(),
  leadingSpace: Dp.create(16),
  middleSpace: Dp.create(8),
  trailingSpace: Dp.create(16),
  shapePessedMorph: Vars.ShapeScheme.Small(),
  shapeMorphAnimationSpring: Vars.SpringScheme.SpatialFast(),
  shapeMorphAnimationCurve: Vars.CurveScheme.ExpressiveSpatialFast(),
  selectedContainerShapeRound: Vars.ShapeScheme.Medium(),
  selectedContainerShapeSquare: Vars.ShapeScheme.Full(),
});

export const Medium = (): Size => ({
  containerHeight: Dp.create(56),
  outlineWidth: Dp.create(1),
  labelStyle: Vars.Typescale.BodyLarge(),
  iconSize: Dp.create(24),
  shapeRound: Vars.ShapeScheme.Full(),
  shapeSquare: Vars.ShapeScheme.Large(),
  leadingSpace: Dp.create(24),
  middleSpace: Dp.create(8),
  trailingSpace: Dp.create(24),
  shapePessedMorph: Vars.ShapeScheme.Medium(),
  shapeMorphAnimationSpring: Vars.SpringScheme.SpatialFast(),
  shapeMorphAnimationCurve: Vars.CurveScheme.ExpressiveSpatialFast(),
  selectedContainerShapeRound: Vars.ShapeScheme.Large(),
  selectedContainerShapeSquare: Vars.ShapeScheme.Full(),
});

export const Large = (): Size => ({
  containerHeight: Dp.create(96),
  outlineWidth: Dp.create(2),
  labelStyle: Vars.Typescale.HeadlineSmall(),
  iconSize: Dp.create(32),
  shapeRound: Vars.ShapeScheme.Full(),
  shapeSquare: Vars.ShapeScheme.ExtraLarge(),
  leadingSpace: Dp.create(48),
  middleSpace: Dp.create(12),
  trailingSpace: Dp.create(48),
  shapePessedMorph: Vars.ShapeScheme.Large(),
  shapeMorphAnimationSpring: Vars.SpringScheme.SpatialFast(),
  shapeMorphAnimationCurve: Vars.CurveScheme.ExpressiveSpatialFast(),
  selectedContainerShapeRound: Vars.ShapeScheme.ExtraLarge(),
  selectedContainerShapeSquare: Vars.ShapeScheme.Full(),
});

export const ExtraLarge = (): Size => ({
  containerHeight: Dp.create(136),
  outlineWidth: Dp.create(3),
  labelStyle: Vars.Typescale.HeadlineLarge(),
  iconSize: Dp.create(40),
  shapeRound: Vars.ShapeScheme.Full(),
  shapeSquare: Vars.ShapeScheme.ExtraLarge(),
  leadingSpace: Dp.create(64),
  middleSpace: Dp.create(16),
  trailingSpace: Dp.create(64),
  shapePessedMorph: Vars.ShapeScheme.Large(),
  shapeMorphAnimationSpring: Vars.SpringScheme.SpatialFast(),
  shapeMorphAnimationCurve: Vars.CurveScheme.ExpressiveSpatialFast(),
  selectedContainerShapeRound: Vars.ShapeScheme.ExtraLarge(),
  selectedContainerShapeSquare: Vars.ShapeScheme.Full(),
});
