import { Vars, MaybeVar, Color, Dp, ShapeRadii, TextStyle, Ui, Opacity, Elevation } from "@internal/prelude";

export interface List {
  readonly segmentGap: Dp,
  readonly containerShape: MaybeVar<ShapeRadii>,
  readonly containerShapeExpand: MaybeVar<ShapeRadii>,
  readonly trailingIconShapeExpand: MaybeVar<ShapeRadii>,
}

export const create = (): List => ({
  segmentGap: Dp.create(2),
  containerShape: Vars.ShapeScheme.Large(),
  containerShapeExpand: Vars.ShapeScheme.Large(),
  trailingIconShapeExpand: Vars.ShapeScheme.Full(),
});

interface Item {
  /** ------------------
   *  Container
   *  ------------------ */
  readonly containerHeight1Line: Dp,
  readonly containerHeight2Line: Dp,
  readonly containerHeight3Line: Dp,

  readonly containerShape: MaybeVar<ShapeRadii>,
  readonly containerShapeExpressive: MaybeVar<ShapeRadii>,
  readonly containerShapeExpressiveDisabled: MaybeVar<ShapeRadii>,
  readonly containerShapeExpressiveHovered: MaybeVar<ShapeRadii>,
  readonly containerShapeExpressiveFocused: MaybeVar<ShapeRadii>,
  readonly containerShapeExpressivePressed: MaybeVar<ShapeRadii>,
  readonly containerShapeExpressiveDragged: MaybeVar<ShapeRadii>,
  readonly containerShapeSelected: MaybeVar<ShapeRadii>,
  readonly containerShapeSelectedExpressive: MaybeVar<ShapeRadii>,
  readonly containerShapeSelectedExpressiveDisabled: MaybeVar<ShapeRadii>,
  readonly containerShapeSelectedExpressiveHovered: MaybeVar<ShapeRadii>,
  readonly containerShapeSelectedExpressiveFocsued: MaybeVar<ShapeRadii>,
  readonly containerShapeSelectedExpressivePressed: MaybeVar<ShapeRadii>,
  readonly containerShapeSelectedExpressiveDragged: MaybeVar<ShapeRadii>,

  readonly containerColor: MaybeVar<Color>,
  readonly containerColorSegmented: MaybeVar<Color>,
  readonly containerColorSelected: MaybeVar<Color>,
  readonly containerColorSelectedDisabled: MaybeVar<Color>,
  readonly containerColorDragged: MaybeVar<Elevation>,
  readonly containerColorExpanded: MaybeVar<Color>,
  readonly containerColorExpandedSegmented: MaybeVar<Color>,

  readonly containerOpacitySelectedDisabled: MaybeVar<Opacity>,

  readonly containerElevation: MaybeVar<Elevation>,

  /** ------------------
   *  Leading Avatar
   *  ------------------ */
  readonly leadingAvatarSize: Dp,
  readonly leadingAvatarShape: MaybeVar<ShapeRadii>,
  readonly leadingAvatarColor: MaybeVar<Color>,
  readonly leadingAvatarLabelStyle: MaybeVar<TextStyle>,
  readonly leadingAvatarLabelColor: MaybeVar<Color>,

  /** ------------------
   *  Leading Video
   *  ------------------ */
  readonly leadingVideoShape: MaybeVar<ShapeRadii>,
  readonly leadingVideoWidth: Dp,
  // NOTE: The specification didn't list this "leadingVideoHeight"
  // token, which likely an error on their part.
  readonly leadingVideoHeight: Dp,
  readonly leadingVideoWidthSmall: Dp,
  readonly leadingVideoWidthLarge: Dp,
  readonly leadingVideoHeightSmall: Dp,
  readonly leadingVideoHeightLarge: Dp,

  /** ------------------
   *  Leading Image
   *  ------------------ */
  readonly leadingImageWidth: Dp,
  readonly leadingImageHeight: Dp,
  readonly leadingImageShape: MaybeVar<ShapeRadii>,
  readonly leadingImageShapeExpressive: MaybeVar<ShapeRadii>,

  /** ------------------
   *  Leading Icon
   *  ------------------ */
  readonly leadingIconSize: Dp,
  readonly leadingIconSizeExpressive: Dp,

  readonly leadingIconColor: MaybeVar<Color>,
  readonly leadingIconColorDisabled: MaybeVar<Color>,
  readonly leadingIconColorHovered: MaybeVar<Color>,
  readonly leadingIconColorFocused: MaybeVar<Color>,
  readonly leadingIconColorPressed: MaybeVar<Color>,
  readonly leadingIconColorDragged: MaybeVar<Color>,
  readonly leadingIconColorSelected: MaybeVar<Color>,
  readonly leadingIconColorSelectedDisabled: MaybeVar<Color>,
  readonly leadingIconColorSelectedHovered: MaybeVar<Color>,
  readonly leadingIconColorSelectedFocused: MaybeVar<Color>,
  readonly leadingIconColorSelectedPressed: MaybeVar<Color>,
  readonly leadingIconColorSelectedDragged: MaybeVar<Color>,

  readonly leadingIconOpacityDisabled: MaybeVar<Opacity>,
  readonly leadingIconOpacitySelectedDisabled: MaybeVar<Opacity>,

  /** ------------------
   *  Label
   *  ------------------ */
  readonly LabelStyle: MaybeVar<TextStyle>,

  readonly labelColor: MaybeVar<Color>,
  readonly labelColorDisabled: MaybeVar<Color>,
  readonly labelColorHovered: MaybeVar<Color>,
  readonly labelColorFocused: MaybeVar<Color>,
  readonly labelColorPressed: MaybeVar<Color>,
  readonly labelColorDragged: MaybeVar<Color>,
  readonly labelColorSelected: MaybeVar<Color>,
  readonly labelColorSelectedDisabled: MaybeVar<Color>,
  readonly labelColorSelectedHovered: MaybeVar<Color>,
  readonly labelColorSelectedFocused: MaybeVar<Color>,
  readonly labelColorSelectedPressed: MaybeVar<Color>,
  readonly labelColorSelectedDragged: MaybeVar<Color>,

  readonly labelOpacityDisabled: MaybeVar<Opacity>,
  readonly labelOpacitySelectedDisabled: MaybeVar<Opacity>,
}

export interface ListStyle {
  readonly listItemContainerColor: MaybeVar<Color>,
  readonly listItemSegmentedContainerColor: MaybeVar<Color>,
  readonly listItemLabelTextColor: MaybeVar<Color>,
  readonly listItemSupportingTextColor: MaybeVar<Color>,
  readonly listItemOverlineColor: MaybeVar<Color>,
  readonly listItemLeadingIconColor: MaybeVar<Color>,
  readonly listItemTrailingIconColor: MaybeVar<Color>,
  readonly listItemUnselectedTrailingIconColor: MaybeVar<Color>,
  readonly listItemTrailingSupportingTextColor: MaybeVar<Color>,
  readonly listItemLeadingAvatarColor: MaybeVar<Color>,
  readonly listItemLeadingAvatarLabelColor: MaybeVar<Color>,
  readonly listItemContainerElevation: MaybeVar<Elevation>,

  readonly listItemSelectedContainerColor: MaybeVar<Color>,
  readonly listItemSelectedLabelTextColor: MaybeVar<Color>,
  readonly listItemSelectedSupportingTextColor: MaybeVar<Color>,
  readonly listItemSelectedTrailingSupportingTextColor: MaybeVar<Color>,
  readonly listItemSelectedLeadingIconColor: MaybeVar<Color>,
  readonly listItemSelectedTrailingIconColor: MaybeVar<Color>,
  readonly listItemSelectedOverlineColor: MaybeVar<Color>,

  readonly listItemDisabledStateLayerColor: MaybeVar<Color>,
  readonly listItemDisabledStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemDisabledLabelTextColor: MaybeVar<Color>,
  readonly listItemDisabledLabelTextOpacity: MaybeVar<Opacity>,
  readonly listItemDisabledSupportingTextColor: MaybeVar<Color>,
  readonly listItemDisabledSupportingTextOpacity: MaybeVar<Opacity>,
  readonly listItemDisabledOverlineColor: MaybeVar<Color>,
  readonly listItemDisabledOverlineOpacity: MaybeVar<Opacity>,
  readonly listItemDisabledLeadingIconColor: MaybeVar<Color>,
  readonly listItemDisabledLeadingIconOpacity: MaybeVar<Opacity>,
  readonly listItemDisabledTrailingIconColor: MaybeVar<Color>,
  readonly listItemDisabledTrailingIconOpacity: MaybeVar<Opacity>,

  readonly listItemSelectedDisabledContainerColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledContainerOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDisabledLabelTextColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledLabelTextOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDisabledSupportingTextColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledSupportingTextOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDisabledTrailingSupportingTextColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledTrailingSupportingTextOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDisabledOverlineColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledOverlineOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDisabledStateLayerColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDisabledLeadingIconColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledLeadingIconOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDisabledTrailingIconColor: MaybeVar<Color>,
  readonly listItemSelectedDisabledTrailingIconOpacity: MaybeVar<Opacity>,

  readonly listItemHoveredStateLayerColor: MaybeVar<Color>,
  readonly listItemHoveredStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemHoveredLabelTextColor: MaybeVar<Color>,
  readonly listItemHoveredLeadingIconColor: MaybeVar<Color>,
  readonly listItemHoveredTrailingIconColor: MaybeVar<Color>,

  readonly listItemSelectedHoveredStateLayerColor: MaybeVar<Color>,
  readonly listItemSelectedHoveredStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedHoveredLabelTextColor: MaybeVar<Color>,
  readonly listItemSelectedHoveredLeadingIconColor: MaybeVar<Color>,
  readonly listItemSelectedHoveredTrailingIconColor: MaybeVar<Color>,

  readonly listItemFocusedStateLayerColor: MaybeVar<Color>,
  readonly listItemFocusedStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemFocusedLabelTextColor: MaybeVar<Color>,
  readonly listItemFocusedLeadingIconColor: MaybeVar<Color>,
  readonly listItemFocusedTrailingIconColor: MaybeVar<Color>,

  readonly listItemFocusedIndicatorColor: MaybeVar<Color>,
  readonly listItemFocusedIndicatorThickness: MaybeVar<Dp>,
  readonly listItemFocusedIndicatorOffset: MaybeVar<Dp>,
  readonly listItemSelectedFocusedStateLayerColor: MaybeVar<Color>,
  readonly listItemSelectedFocusedStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedFocusedLabelTextColor: MaybeVar<Color>,
  readonly listItemSelectedFocusedLeadingIconColor: MaybeVar<Color>,
  readonly listItemSelectedFocusedTrailingIconColor: MaybeVar<Color>,

  readonly listItemPressedStateLayerColor: MaybeVar<Color>,
  readonly listItemPressedStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemPressedLabelTextColor: MaybeVar<Color>,
  readonly listItemPressedLeadingIconColor: MaybeVar<Color>,
  readonly listItemPressedTrailingIconColor: MaybeVar<Color>,

  readonly listItemSelectedPressedStateLayerColor: MaybeVar<Color>,
  readonly listItemSelectedPressedStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedPressedLabelTextColor: MaybeVar<Color>,
  readonly listItemSelectedPressedTrailingIconColor: MaybeVar<Color>,
  readonly listItemSelectedPressedLeadingIconColor: MaybeVar<Color>,

  // Color / Dragged (Baseline Only)
  readonly listItemDraggedContainerColor: MaybeVar<Elevation>,
  readonly listItemDraggedLabelTextColor: MaybeVar<Color>,
  readonly listItemSelectedDraggedLabelTextColor: MaybeVar<Color>,
  readonly listItemDraggedStateLayerColor: MaybeVar<Color>,
  readonly listItemDraggedStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemSelectedDraggedStateLayerColor: MaybeVar<Color>,
  readonly listItemSelectedDraggedStateLayerOpacity: MaybeVar<Opacity>,
  readonly listItemDraggedLeadingIconColor: MaybeVar<Color>,
  readonly listItemSelectedDraggedLeadingIconColor: MaybeVar<Color>,
  readonly listItemDraggedTrailingIconColor: MaybeVar<Color>,
  readonly listItemSelectedDraggedTrailingIconColor: MaybeVar<Color>,

  readonly listItemLeadingSpace: Dp,
  readonly listItemTrailingSpace: Dp,
  readonly listItemTopSpace: Dp,
  readonly listItemBottomSpace: Dp,
  readonly listItemBetweenSpace: Dp,
  readonly listItemDividerLeadingSpace: Dp,
  readonly listItemDividerTrailingSpace: Dp,
  readonly listItemDividerTopSpace: Dp,
  readonly listItemDividerBottomSpace: Dp,
  readonly listSegmentGap: Dp,

  readonly listContainerShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerDisabledExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerHoveredExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerFocusedExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerPressedExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerDraggedExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerSelectedExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerSelectedDisabledExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerSelectedHoveredExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerSelectedFocsuedExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerSelectedPressedExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemContainerSelectedDraggedExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemLeadingAvatarShape: MaybeVar<ShapeRadii>,
  readonly listItemLeadingVideoShape: MaybeVar<ShapeRadii>,
  readonly listItemLeadingImageShape: MaybeVar<ShapeRadii>,
  readonly listItemLeadingImageExpressiveShape: MaybeVar<ShapeRadii>,
  readonly listItemSelectedContainerShape: MaybeVar<ShapeRadii>,

  readonly listItemLeadingAvatarSize: Dp,
  readonly listItemLeadingAvatarLabelRole: MaybeVar<TextStyle>,
  readonly listItemLeadingIconSize: Dp,
  readonly listItemLeadingIconExpressiveSize: Dp,
  readonly listItemLeadingImageWidth: Dp,
  readonly listItemLeadingImageHeight: Dp,
  readonly listItemLeadingVideoWidth: Dp,
  readonly listItemSmallLeadingVideoWidth: Dp,
  readonly listItemSmallLeadingVideoHeight: Dp,
  readonly listItemLargeLeadingVideoWidth: Dp,
  readonly listItemLargeLeadingVideoHeight: Dp,
  readonly listItem1LineContainerHeight: Dp,
  readonly listItem2LineContainerHeight: Dp,
  readonly listItem3LineContainerHeight: Dp,
  readonly listItemTrailingIconSize: Dp,
  readonly listItemTrailingIconExpressiveSize: Dp,
  readonly listItemLabelTextRole: MaybeVar<TextStyle>,
  readonly listItemTrailingSupportingTextRole: MaybeVar<TextStyle>,
  readonly listItemSupportingTextRole: MaybeVar<TextStyle>,
  readonly listItemOverlineRole: MaybeVar<TextStyle>,

  readonly listExpandExpandedListItemContainerColor: MaybeVar<Color>,
  readonly listExpandExpandedListItemSegmentedContainerColor: MaybeVar<Color>,
  readonly listExpandCollapsedListItemTrailingIconContainerColor: MaybeVar<Color>,
  readonly listExpandCollapsedListItemTrailingIconIconColor: MaybeVar<Color>,
  readonly listExpandExpandedListItemTrailingIconContainerColor: MaybeVar<Color>,
  readonly listExpandExpandedListItemTrailingIconIconColor: MaybeVar<Color>,

  readonly listExpandContainerShape: MaybeVar<ShapeRadii>,
  readonly listExpandTrailingIconShape: MaybeVar<ShapeRadii>,
}

export const create = (): ListStyle => {
  return {
    listItemContainerColor: Vars.ColorScheme.Surface(),
    listItemSegmentedContainerColor: Vars.ColorScheme.Surface(),
    listItemLabelTextColor: Vars.ColorScheme.OnSurface(),
    listItemSupportingTextColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemOverlineColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemLeadingIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemTrailingIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemUnselectedTrailingIconColor: Vars.ColorScheme.OnSurface(),
    listItemTrailingSupportingTextColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemLeadingAvatarColor: Vars.ColorScheme.PrimaryContainer(),
    listItemLeadingAvatarLabelColor: Vars.ColorScheme.OnPrimaryContainer(),
    listItemContainerElevation: Vars.ElevationScheme.Level0(),

    listItemSelectedContainerColor: Vars.ColorScheme.SecondaryContainer(),
    listItemSelectedLabelTextColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedSupportingTextColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedTrailingSupportingTextColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedLeadingIconColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedTrailingIconColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedOverlineColor: Vars.ColorScheme.OnSecondaryContainer(),

    listItemDisabledStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemDisabledStateLayerOpacity: Ui.create(0.1),
    listItemDisabledLabelTextColor: Vars.ColorScheme.OnSurface(),
    listItemDisabledLabelTextOpacity: Ui.create(0.38),
    listItemDisabledSupportingTextColor: Vars.ColorScheme.OnSurface(),
    listItemDisabledSupportingTextOpacity: Ui.create(0.38),
    listItemDisabledOverlineColor: Vars.ColorScheme.OnSurface(),
    listItemDisabledOverlineOpacity: Ui.create(0.38),
    listItemDisabledLeadingIconColor: Vars.ColorScheme.OnSurface(),
    listItemDisabledLeadingIconOpacity: Ui.create(0.38),
    listItemDisabledTrailingIconColor: Vars.ColorScheme.OnSurface(),
    listItemDisabledTrailingIconOpacity: Ui.create(0.38),

    listItemSelectedDisabledContainerColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledContainerOpacity: Ui.create(0.38),
    listItemSelectedDisabledLabelTextColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledLabelTextOpacity: Ui.create(0.38),
    listItemSelectedDisabledSupportingTextColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledSupportingTextOpacity: Ui.create(0.38),
    listItemSelectedDisabledTrailingSupportingTextColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledTrailingSupportingTextOpacity: Ui.create(0.38),
    listItemSelectedDisabledOverlineColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledOverlineOpacity: Ui.create(0.38),
    listItemSelectedDisabledStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledStateLayerOpacity: Ui.create(0.1),
    listItemSelectedDisabledLeadingIconColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledLeadingIconOpacity: Ui.create(0.38),
    listItemSelectedDisabledTrailingIconColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDisabledTrailingIconOpacity: Ui.create(0.38),

    listItemHoveredStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemHoveredStateLayerOpacity: Vars.Opacities.Hovered(),
    listItemHoveredLabelTextColor: Vars.ColorScheme.OnSurface(),
    listItemHoveredLeadingIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemHoveredTrailingIconColor: Vars.ColorScheme.OnSurfaceVariant(),

    listItemSelectedHoveredStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedHoveredStateLayerOpacity: Vars.Opacities.Hovered(),
    listItemSelectedHoveredLabelTextColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedHoveredLeadingIconColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedHoveredTrailingIconColor: Vars.ColorScheme.OnSurface(),

    listItemFocusedStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemFocusedStateLayerOpacity: Vars.Opacities.Focused(),
    listItemFocusedLabelTextColor: Vars.ColorScheme.OnSurface(),
    listItemFocusedLeadingIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemFocusedTrailingIconColor: Vars.ColorScheme.OnSurfaceVariant(),

    listItemFocusedIndicatorColor: Vars.ColorScheme.Secondary(),
    listItemFocusedIndicatorThickness: Vars.FocusIndicator.Thickness(),
    listItemFocusedIndicatorOffset: Vars.FocusIndicator.InnerOffset(),
    listItemSelectedFocusedStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedFocusedStateLayerOpacity: Vars.Opacities.Focused(),
    listItemSelectedFocusedLabelTextColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedFocusedLeadingIconColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedFocusedTrailingIconColor: Vars.ColorScheme.OnSurface(),

    listItemPressedStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemPressedStateLayerOpacity: Vars.Opacities.Pressed(),
    listItemPressedLabelTextColor: Vars.ColorScheme.OnSurface(),
    listItemPressedLeadingIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemPressedTrailingIconColor: Vars.ColorScheme.OnSurfaceVariant(),

    listItemSelectedPressedStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedPressedStateLayerOpacity: Vars.Opacities.Pressed(),
    listItemSelectedPressedLabelTextColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemSelectedPressedTrailingIconColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedPressedLeadingIconColor: Vars.ColorScheme.OnSurface(),

    // Color / Dragged (Baseline Only)
    listItemDraggedContainerColor: Vars.ElevationScheme.Level4(),
    listItemDraggedLabelTextColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDraggedLabelTextColor: Vars.ColorScheme.OnSecondaryContainer(),
    listItemDraggedStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemDraggedStateLayerOpacity: Vars.Opacities.Dragged(),
    listItemSelectedDraggedStateLayerColor: Vars.ColorScheme.OnSurface(),
    listItemSelectedDraggedStateLayerOpacity: Vars.Opacities.Dragged(),
    listItemDraggedLeadingIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemSelectedDraggedLeadingIconColor: Vars.ColorScheme.OnSurface(),
    listItemDraggedTrailingIconColor: Vars.ColorScheme.OnSurfaceVariant(),
    listItemSelectedDraggedTrailingIconColor: Vars.ColorScheme.OnSurface(),

    listItemLeadingSpace: Dp.create(16),
    listItemTrailingSpace: Dp.create(16),
    listItemTopSpace: Dp.create(10),
    listItemBottomSpace: Dp.create(10),
    listItemBetweenSpace: Dp.create(12),
    listItemDividerLeadingSpace: Dp.create(16),
    listItemDividerTrailingSpace: Dp.create(16),
    listItemDividerTopSpace: Dp.create(0),
    listItemDividerBottomSpace: Dp.create(0),

    listItemContainerShape: Vars.ShapeScheme.None(),
    listItemContainerExpressiveShape: Vars.ShapeScheme.ExtraSmall(),
    listItemContainerDisabledExpressiveShape: Vars.ShapeScheme.ExtraSmall(),
    listItemContainerHoveredExpressiveShape: Vars.ShapeScheme.Medium(),
    listItemContainerFocusedExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerPressedExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerDraggedExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerSelectedExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerSelectedDisabledExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerSelectedHoveredExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerSelectedFocsuedExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerSelectedPressedExpressiveShape: Vars.ShapeScheme.Large(),
    listItemContainerSelectedDraggedExpressiveShape: Vars.ShapeScheme.Large(),
    listItemLeadingAvatarShape: Vars.ShapeScheme.Full(),
    listItemLeadingVideoShape: Vars.ShapeScheme.Small(),
    listItemLeadingImageShape: Vars.ShapeScheme.None(),
    listItemLeadingImageExpressiveShape: Vars.ShapeScheme.Small(),
    listItemSelectedContainerShape: Vars.ShapeScheme.Large(),

    listItemLeadingAvatarSize: Dp.create(40),
    listItemLeadingAvatarLabelRole: Vars.Typescale.TitleMedium(),
    listItemLeadingIconSize: Dp.create(24),
    listItemLeadingIconExpressiveSize: Dp.create(20),
    listItemLeadingImageWidth: Dp.create(56),
    listItemLeadingImageHeight: Dp.create(56),
    listItemLeadingVideoWidth: Dp.create(100),
    listItemSmallLeadingVideoWidth: Dp.create(100),
    listItemSmallLeadingVideoHeight: Dp.create(56),
    listItemLargeLeadingVideoWidth: Dp.create(114),
    listItemLargeLeadingVideoHeight: Dp.create(64),
    listItem1LineContainerHeight: Dp.create(56),
    listItem2LineContainerHeight: Dp.create(72),
    listItem3LineContainerHeight: Dp.create(88),
    listItemTrailingIconSize: Dp.create(24),
    listItemTrailingIconExpressiveSize: Dp.create(20),
    listItemLabelTextRole: Vars.Typescale.BodyLarge(),
    listItemTrailingSupportingTextRole: Vars.Typescale.LabelSmall(),
    listItemSupportingTextRole: Vars.Typescale.BodyMedium(),
    listItemOverlineRole: Vars.Typescale.LabelSmall(),

    listExpandExpandedListItemContainerColor: Vars.ColorScheme.Surface(),
    listExpandExpandedListItemSegmentedContainerColor: Vars.ColorScheme.Surface(),
    listExpandCollapsedListItemTrailingIconContainerColor: Vars.ColorScheme.Surface(),
    listExpandCollapsedListItemTrailingIconIconColor: Vars.ColorScheme.OnSurface(),
    listExpandExpandedListItemTrailingIconContainerColor: Vars.ColorScheme.SurfaceContainer(),
    listExpandExpandedListItemTrailingIconIconColor: Vars.ColorScheme.OnSurface(),

  };
};