import { Vars, MaybeVar, Color, Dp, ShapeRadii, ShapesRef, Ui, FocusIndicatorRef } from "@internal/prelude";

export interface Switch {
  readonly selectedIconColor: MaybeVar<Color>,
  readonly selectedIconSize: Dp,
  readonly unselectedIconColor: MaybeVar<Color>,
  readonly unselectedIconSize: Dp,
  readonly trackHeight: Dp,
  readonly trackWidth: Dp,
  readonly trackOutlineColor: MaybeVar<Color>,
  readonly trackOutlineWidth: Dp,
  readonly trackShape: MaybeVar<ShapeRadii>,
  readonly selectedTrackColor: MaybeVar<Color>,
  readonly unselectedTrackColor: MaybeVar<Color>,

  readonly unselectedHandleHeight: Dp,
  readonly withIconHandleHeight: Dp,
  readonly selectedHandleHeight: Dp,
  readonly pressedHandleHeight: Dp,
  readonly unselectedHandleWidth: Dp,
  readonly withIconHandleWidth: Dp,
  readonly selectedHandleWidth: Dp,
  readonly pressedHandleWidth: Dp,
  readonly handleShape: MaybeVar<ShapeRadii>,
  readonly selectedHandleColor: MaybeVar<Color>,
  readonly unselectedHandleColor: MaybeVar<Color>,
  readonly stateLayerSize: Dp,
  readonly stateLayerShape: MaybeVar<ShapeRadii>,

  readonly disabledSelectedIconColor: MaybeVar<Color>,
  readonly disabledSelectedIconOpacity: MaybeVar<Opacity>,
  readonly disabledUnselectedIconColor: MaybeVar<Color>,
  readonly disabledUnselectedIconOpacity: MaybeVar<Opacity>,
  readonly disabledTrackOpacity: MaybeVar<Opacity>,
  readonly disabledSelectedTrackColor: MaybeVar<Color>,
  readonly disabledUnselectedTrackColor: MaybeVar<Color>,
  readonly disabledUnselectedTrackOutlineColor: MaybeVar<Color>,
  readonly disabledUnselectedHandleOpacity: MaybeVar<Opacity>,
  readonly disabledSelectedHandleOpacity: MaybeVar<Opacity>,
  readonly disabledSelectedHandleColor: MaybeVar<Color>,
  readonly disabledUnselectedHandleColor: MaybeVar<Color>,

  readonly selectedHoverIconColor: MaybeVar<Color>,
  readonly unselectedHoverIconColor: MaybeVar<Color>,
  readonly selectedHoverTrackColor: MaybeVar<Color>,
  readonly selectedHoverStateLayerColor: MaybeVar<Color>,
  readonly selectedHoverStateLayerOpacity: MaybeVar<Opacity>,
  readonly unselectedHoverTrackColor: MaybeVar<Color>,
  readonly unselectedHoverTrackOutlineColor: MaybeVar<Color>,
  readonly unselectedHoverStateLayerColor: MaybeVar<Color>,
  readonly unselectedHoverStateLayerOpacity: MaybeVar<Opacity>,
  readonly selectedHoverHandleColor: MaybeVar<Color>,
  readonly unselectedHoverHandleColor: MaybeVar<Color>,

  readonly FocusedIndicatorColor: MaybeVar<Color>,
  readonly FocusedIndicatorThickness: MaybeVar<Dp>,
  readonly FocusedIndicatorOffset: MaybeVar<Dp>,
  readonly selectedFocusedIconColor: MaybeVar<Color>,
  readonly unselectedFocusedIconColor: MaybeVar<Color>,
  readonly selectedFocusedTrackColor: MaybeVar<Color>,
  readonly selectedFocusedStateLayerColor: MaybeVar<Color>,
  readonly selectedFocusedStateLayerOpacity: MaybeVar<Opacity>,
  readonly unselectedFocusedTrackColor: MaybeVar<Color>,
  readonly unselectedFocusedTrackOutlineColor: MaybeVar<Color>,
  readonly unselectedFocusedStateLayerColor: MaybeVar<Color>,
  readonly unselectedFocusedStateLayerOpacity: MaybeVar<Opacity>,
  readonly selected_focusHandleColor: MaybeVar<Color>,
  readonly unselected_focusHandleColor: MaybeVar<Color>,

  readonly selectedPressedIconColor: MaybeVar<Color>,
  readonly unselectedPressedIconColor: MaybeVar<Color>,
  readonly selectedPressedTrackColor: MaybeVar<Color>,
  readonly selectedPressedStateLayerColor: MaybeVar<Color>,
  readonly selectedPressedStateLayerOpacity: MaybeVar<Opacity>,
  readonly unselectedPressedTrackColor: MaybeVar<Color>,
  readonly unselectedPressedTrackOutlineColor: MaybeVar<Color>,
  readonly unselectedPressedStateLayerColor: MaybeVar<Color>,
  readonly unselectedPressedStateLayerOpacity: MaybeVar<Opacity>,
  readonly selectedPressedHandleColor: MaybeVar<Color>,
  readonly unselectedPressedHandleColor: MaybeVar<Color>,
}

export const create = (): Switch => {
  return {
    selectedIconColor: Vars.ColorScheme.Primary(),
    selectedIconSize: Dp.create(16),
    unselectedIconColor: Vars.ColorScheme.SurfaceContainerHighest(),
    unselectedIconSize: Dp.create(16),
    trackHeight: Dp.create(32),
    trackWidth: Dp.create(52),
    trackOutlineColor: Vars.ColorScheme.Outline(),
    trackOutlineWidth: Dp.create(2),
    trackShape: Vars.ShapeScheme.Full(),
    selectedTrackColor: Vars.ColorScheme.Primary(),
    unselectedTrackColor: Vars.ColorScheme.SurfaceContainerHighest(),

    unselectedHandleHeight: Dp.create(16),
    withIconHandleHeight: Dp.create(24),
    selectedHandleHeight: Dp.create(24),
    pressedHandleHeight: Dp.create(28),
    unselectedHandleWidth: Dp.create(16),
    withIconHandleWidth: Dp.create(24),
    selectedHandleWidth: Dp.create(24),
    pressedHandleWidth: Dp.create(28),
    handleShape: Vars.ShapeScheme.Full(),
    selectedHandleColor: Vars.ColorScheme.OnPrimary(),
    unselectedHandleColor: Vars.ColorScheme.Outline(),
    stateLayerSize: Dp.create(40),
    stateLayerShape: Vars.ShapeScheme.Full(),

    disabledSelectedIconColor: Vars.ColorScheme.OnSurface(),
    disabledSelectedIconOpacity: Ui.create(0.38),
    disabledUnselectedIconColor: Vars.ColorScheme.SurfaceContainerHighest(),
    disabledUnselectedIconOpacity: Ui.create(0.38),
    disabledTrackOpacity: Ui.create(0.12),
    disabledSelectedTrackColor: Vars.ColorScheme.OnSurface(),
    disabledUnselectedTrackColor: Vars.ColorScheme.SurfaceContainerHighest(),
    disabledUnselectedTrackOutlineColor: Vars.ColorScheme.OnSurface(),
    disabledUnselectedHandleOpacity: Ui.create(0.38),
    disabledSelectedHandleOpacity: Ui.create(1),
    disabledSelectedHandleColor: Vars.ColorScheme.Surface(),
    disabledUnselectedHandleColor: Vars.ColorScheme.OnSurface(),

    selectedHoverIconColor: Vars.ColorScheme.Primary(),
    unselectedHoverIconColor: Vars.ColorScheme.SurfaceContainerHighest(),
    selectedHoverTrackColor: Vars.ColorScheme.Primary(),
    selectedHoverStateLayerColor: Vars.ColorScheme.Primary(),
    selectedHoverStateLayerOpacity: Vars.Opacities.Hovered(),
    unselectedHoverTrackColor: Vars.ColorScheme.SurfaceContainerHighest(),
    unselectedHoverTrackOutlineColor: Vars.ColorScheme.Outline(),
    unselectedHoverStateLayerColor: Vars.ColorScheme.OnSurface(),
    unselectedHoverStateLayerOpacity: Vars.Opacities.Hovered(),
    selectedHoverHandleColor: Vars.ColorScheme.PrimaryContainer(),
    unselectedHoverHandleColor: Vars.ColorScheme.OnSurfaceVariant(),

    FocusedIndicatorColor: Vars.ColorScheme.Secondary(),
    FocusedIndicatorThickness: Vars.FocusIndicator.Thickness(),
    FocusedIndicatorOffset: Vars.FocusIndicator.OuterOffset(),
    selectedFocusedIconColor: Vars.ColorScheme.Primary(),
    unselectedFocusedIconColor: Vars.ColorScheme.SurfaceContainerHighest(),
    selectedFocusedTrackColor: Vars.ColorScheme.Primary(),
    selectedFocusedStateLayerColor: Vars.ColorScheme.Primary(),
    selectedFocusedStateLayerOpacity: Vars.Opacities.Focused(),
    unselectedFocusedTrackColor: Vars.ColorScheme.SurfaceContainerHighest(),
    unselectedFocusedTrackOutlineColor: Vars.ColorScheme.Outline(),
    unselectedFocusedStateLayerColor: Vars.ColorScheme.OnSurface(),
    unselectedFocusedStateLayerOpacity: Vars.Opacities.Focused(),
    selected_focusHandleColor: Vars.ColorScheme.PrimaryContainer(),
    unselected_focusHandleColor: Vars.ColorScheme.OnSurfaceVariant(),

    selectedPressedIconColor: Vars.ColorScheme.Primary(),
    unselectedPressedIconColor: Vars.ColorScheme.SurfaceContainerHighest(),
    selectedPressedTrackColor: Vars.ColorScheme.Primary(),
    selectedPressedStateLayerColor: Vars.ColorScheme.Primary(),
    selectedPressedStateLayerOpacity: Vars.Opacities.Pressed(),
    unselectedPressedTrackColor: Vars.ColorScheme.SurfaceContainerHighest(),
    unselectedPressedTrackOutlineColor: Vars.ColorScheme.Outline(),
    unselectedPressedStateLayerColor: Vars.ColorScheme.OnSurface(),
    unselectedPressedStateLayerOpacity: Vars.Opacities.Pressed(),
    selectedPressedHandleColor: Vars.ColorScheme.PrimaryContainer(),
    unselectedPressedHandleColor: Vars.ColorScheme.OnSurfaceVariant(),
  };
};